---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen zur BlueXP Klassifizierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== BlueXP Klassifizierungsservice

Die folgenden Fragen bieten ein allgemeines Verständnis der BlueXP Klassifizierung.



=== Wie funktioniert die BlueXP Klassifizierung?

Die BlueXP -Klassifizierung implementiert eine weitere KI-Schicht zusammen mit dem BlueXP -System und den Storage-Systemen. Anschließend werden die Daten auf Volumes, Buckets, Datenbanken und anderen Storage-Konten überprüft und die gefundenen Dateneinblicke indiziert. Die BlueXP Klassifizierung nutzt sowohl künstliche Intelligenz als auch natürliche Sprachverarbeitung, im Gegensatz zu alternativen Lösungen, die häufig auf regulären Ausdrücken und Mustervergleichen basieren.

Die BlueXP Klassifizierung verwendet KI, um ein kontextbezogenes Verständnis der Daten für eine genaue Erkennung und Klassifizierung zu ermöglichen. Der Fokus liegt auf KI, da sie für moderne Datentypen und Skalierungen konzipiert wurde. Er versteht auch den Datenkontext und sorgt so für starke, präzise, Erkennungs- und Klassifizierungsmöglichkeiten.

link:concept-cloud-compliance.html["Erfahren Sie mehr über die BlueXP Klassifizierung"].



=== Verfügt die BlueXP Klassifizierung über EINE REST-API, die auch mit Tools von Drittanbietern funktioniert?

Ja, die BlueXP -Klassifizierung hat eine REST-API für die unterstützten Funktionen in der BlueXP -Klassifizierungsversion, die Teil der BlueXP  Kernplattform ist. Siehe link:api-classification.html["API-Dokumentation"].



=== Ist die BlueXP -Klassifizierung über die Cloud Marketplaces verfügbar?

Die BlueXP -Klassifizierung ist Teil der BlueXP -Kernfunktionen, so dass Sie die Marktplätze für diesen Service nicht nutzen müssen.



== BlueXP Klassifizierungsscan und -Analysen

Die folgenden Fragen beziehen sich auf die Leistung von BlueXP  Klassifikationsscans und die Analysen.



=== Wie oft werden meine Daten durch die BlueXP Klassifizierung gescannt?

Während der erste Scan Ihrer Daten etwas Zeit in Anspruch nehmen kann, untersuchen nachfolgende Scans nur die inkrementellen Änderungen, was die Systemscanzeiten verkürzt. Die BlueXP Klassifizierung scannt Ihre Daten kontinuierlich nach Round Robin-Verfahren und bietet Ihnen sechs Repositorys gleichzeitig, sodass alle geänderten Daten sehr schnell klassifiziert werden.

link:task-scanning-overview.html["Lesen Sie, wie Scans funktionieren"].

Die BlueXP -Klassifizierung scannt Datenbanken nur einmal pro Tag, Datenbanken werden nicht wie andere Datenquellen kontinuierlich gescannt.

Datenscans haben keine nennenswerten Auswirkungen auf Ihre Storage-Systeme und Ihre Daten.



=== Ist die Scanleistung unterschiedlich?

Die Scan-Performance kann je nach Netzwerkbandbreite und durchschnittlicher Dateigröße in der Umgebung variieren. Es kann auch von der Größe des Host-Systems abhängen (entweder in der Cloud oder lokal). Weitere Informationen finden Sie unter link:concept-cloud-compliance.html["Die BlueXP Klassifizierungsinstanz"] und link:task-deploy-overview.html["Implementieren der BlueXP Klassifizierung"] .

Wenn Sie zunächst neue Datenquellen hinzufügen, können Sie auch nur einen „Mapping“ (nur Mapping)-Scan statt eines vollständigen „Classification“ (Map & Classify)-Scans durchführen. Das Mapping kann auf Ihren Datenquellen sehr schnell durchgeführt werden, da es nicht auf Dateien zugegriffen wird, um die darin enthaltenen Daten zu sehen. link:task-scanning-overview.html["Sehen Sie den Unterschied zwischen einer Mapping- und Klassifizierungsscan"].



=== Kann ich meine Daten mithilfe der BlueXP Klassifizierung durchsuchen?

Die BlueXP Klassifizierung bietet umfangreiche Suchfunktionen, die das Suchen nach einer bestimmten Datei oder einem Datenelement über alle verbundenen Quellen hinweg erleichtern. Die BlueXP Klassifizierung ermöglicht Benutzern eine umfassendere Suche als nur die Inhalte der Metadaten. Es ist ein sprachunabhängiger Dienst, der auch die Dateien lesen und eine Vielzahl sensibler Datentypen, wie Namen und IDs, analysieren kann. So können Benutzer beispielsweise sowohl strukturierte als auch unstrukturierte Datenspeicher durchsuchen, um Daten zu finden, die von Datenbanken bis zu Benutzerdateien ausgetreten sind, und dies unter Verletzung von Unternehmensrichtlinien. Suchvorgänge können für einen späteren Zeitpunkt gespeichert werden. Richtlinien können erstellt werden, um die Ergebnisse zu einer festgelegten Häufigkeit zu suchen und entsprechend zu reagieren.

Sobald die entsprechenden Dateien gefunden wurden, können die Merkmale aufgelistet werden, einschließlich Tags, Konto der Arbeitsumgebung, Bucket, Dateipfad Kategorie (aus Klassifizierung), Dateigröße, letzte Änderung, Berechtigungsstatus, Duplikate, Empfindlichkeitsstufe, persönliche Daten, sensible Datentypen innerhalb der Datei, Eigentümer, Dateityp, Dateigröße, Erstellungszeit, Datei-Hash, unabhängig davon, ob die Daten einer Person zugewiesen wurden, die ihre Aufmerksamkeit sucht, und vieles mehr. Filter können auf Merkmale angewendet werden, die nicht relevant sind.

Die BlueXP -Klassifizierung verfügt außerdem über rollenbasierte Zugriffssteuerung (RBAC), mit der Dateien verschoben oder gelöscht werden können, sofern die entsprechenden Berechtigungen vorliegen. Wenn die richtigen Berechtigungen nicht vorhanden sind, können die Aufgaben einer Person in der Organisation zugewiesen werden, die über die entsprechenden Berechtigungen verfügt.



== BlueXP Klassifizierungsmanagement und Datenschutz

Die folgenden Fragen enthalten Informationen zum Management von BlueXP Klassifizierungs- und Datenschutzeinstellungen.



=== Wie aktiviere oder deaktiviere ich die BlueXP -Klassifizierung?

Zunächst müssen Sie eine Instanz der BlueXP Klassifizierung in BlueXP oder auf einem lokalen System implementieren. Sobald die Instanz ausgeführt wird, können Sie den Dienst auf vorhandenen Arbeitsumgebungen, Datenbanken und anderen Datenquellen über die Registerkarte *Konfiguration* oder durch Auswahl einer bestimmten Arbeitsumgebung aktivieren. link:task-getting-started-compliance.html["Erste Schritte"].


NOTE: Durch die Aktivierung der BlueXP Klassifizierung einer Datenquelle wird ein sofortiger erster Scan durchgeführt. Ergebnisse des Scans werden kurz danach angezeigt.

Sie können die BlueXP Klassifizierung für das Scannen einzelner Arbeitsumgebungen, Datenbanken oder Dateifreigabegruppen auf der Seite BlueXP Klassifizierungskonfiguration deaktivieren. Siehe link:task-managing-compliance.html["Datenquellen aus der BlueXP Klassifizierung entfernen"].

Um die BlueXP Klassifizierungsinstanz vollständig zu entfernen, können Sie die BlueXP Klassifizierungsinstanz manuell aus dem Portal Ihres Cloud-Providers oder Ihrem lokalen Standort entfernen.



=== Kann der Dienst Scandaten in bestimmten Verzeichnissen ausschließen?

Ja. Wenn die BlueXP Klassifizierung Scandaten in bestimmten Quellverzeichnissen ausschließen soll, können Sie der Klassifizierungs-Engine diese Liste bereitstellen. Nach Anwendung dieser Änderung schließt die BlueXP Klassifizierung Scandaten in den angegebenen Verzeichnissen aus. link:task-exclude-scan-paths.html["Weitere Informationen ."].



=== Werden Snapshots gescannt, die sich auf ONTAP-Volumes befinden?

Nein Durch die BlueXP Klassifizierung werden Snapshots nicht gescannt, da der Inhalt mit dem Inhalt des Volume identisch ist.



=== Was geschieht, wenn das Daten-Tiering auf Ihren ONTAP Volumes aktiviert ist?

Wenn die BlueXP -Klassifizierung Volumes scannt, die kalte Daten mithilfe von nur-Mapping-Scans in Objekt-Storage verschoben haben, werden alle Daten gescannt, die sich auf lokalen Festplatten befinden, und kalte Daten, die in Objekt-Storage verschoben wurden. Dies gilt auch für Produkte, die nicht von NetApp stammen und Tiering implementieren.

Der Scan „nur Mapping“ heizt die kalten Daten nicht auf – er bleibt kalt und verbleibt im Objektspeicher. Wenn Sie hingegen den Map & Classify-Scan durchführen, könnten einige Konfigurationen die kalten Daten aufheizen.



== Arten von Quellsystemen und Datentypen

Die folgenden Fragen beziehen sich auf die Art des zu scannenden Speichers und die Arten der gescannten Daten.



=== Gibt es Einschränkungen bei der Bereitstellung in einer Regierungsregion?

Die BlueXP Klassifizierung wird unterstützt, wenn der Connector in einer Regierungsregion (AWS GovCloud, Azure Gov oder Azure DoD) bereitgestellt wird – auch als „eingeschränkter Modus“ bezeichnet.



=== Welche Datenquellen kann ich scannen, wenn ich die BlueXP-Klassifizierung auf einer Website ohne Internetzugang installiere?

Die BlueXP Klassifizierung kann nur Daten aus lokalen Datenquellen am lokalen Standort scannen. Derzeit kann die BlueXP Klassifizierung folgende lokale Datenquellen scannen – im „privaten Modus“, auch als „dunkle“ Site bezeichnet:

* On-Premises ONTAP Systeme
* Datenbankschemas
* Objekt-Storage, der das Simple Storage Service (S3)-Protokoll verwendet


Siehe link:concept-cloud-compliance.html["Unterstützte Arbeitsumgebungen und Datenquellen"].



=== Welche Dateitypen werden unterstützt?

Die BlueXP Klassifizierung scannt alle Dateien nach Kategorien- und Metadaten und zeigt alle Dateitypen im Abschnitt „Dateitypen“ des Dashboards an.

Wenn die BlueXP Klassifizierung personenbezogene Daten erkennt oder eine DSAR-Suche durchführt, werden nur die folgenden Dateiformate unterstützt:

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== Welche Arten von Daten und Metadaten werden durch die BlueXP Klassifizierung erfasst?

Die BlueXP Klassifizierung ermöglicht Ihnen die Durchführung eines allgemeinen „Mapping“-Scans oder eines vollständigen „Klassifizierungs“-Scans für Datenquellen. Das Mapping bietet nur einen Überblick über Ihre Daten auf hoher Ebene, während die Klassifizierung ein tiefes Scannen Ihrer Daten ermöglicht. Das Mapping kann auf Ihren Datenquellen sehr schnell durchgeführt werden, da es nicht auf Dateien zugegriffen wird, um die darin enthaltenen Daten zu sehen.

* *Data Mapping Scan (Mapping only Scan)*: BlueXP  Classification scannt nur die Metadaten. Dies ist nützlich für das allgemeine Datenmanagement und die Datenverwaltung, für eine schnelle Projektabwicklung, für sehr große Bestände und für die Priorisierung. Die Datenzuordnung basiert auf Metadaten und gilt als *fast* Scan.
+
Nach einem schnellen Scan können Sie einen Daten-Mapping-Bericht erstellen. Dieser Bericht bietet einen Überblick über die in Ihren Datenquellen gespeicherten Daten, um Sie bei Entscheidungen zu Ressourcenauslastung, Migration, Backup-, Sicherheits- und Compliance-Prozessen zu unterstützen.

* *Data classification Deep Scan (Map & Classify Scan)*: BlueXP -Klassifikations-Scans mit Standardprotokollen und nur-Lese-Berechtigung in Ihren Umgebungen. Ausgewählte Dateien werden nach sensiblen Daten, privaten Informationen und Ransomware-Problemen geöffnet und gescannt, die damit verbunden sind.
+
Nach einem vollständigen Scan gibt es zahlreiche zusätzliche BlueXP Klassifizierungsfunktionen, die Sie auf Ihre Daten anwenden können, beispielsweise das Anzeigen und Optimieren von Daten auf der Seite „Datenuntersuchung“, das Suchen nach Namen in Dateien, das Kopieren, Verschieben und Löschen von Quelldateien usw.



Die BlueXP Klassifizierung erfasst Metadaten wie z. B. Dateiname, -Berechtigungen, -Erstellungszeit, letzter Zugriff und letzte Änderung. Dies umfasst alle Metadaten, die auf der Seite „Dateninvikatcdion-Details“ und in „Dateninvizationsberichte“ angezeigt werden.

Mit der BlueXP -Klassifizierung können viele Arten von privaten Daten identifiziert werden, wie z. B. personenbezogene Daten (PII) und sensible personenbezogene Daten (SPII). Weitere Informationen zu privaten Daten finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Kategorien von privaten Daten, die durch die BlueXP Klassifizierung gescannt werden"].



=== Kann ich die BlueXP Klassifizierungsinformationen auf bestimmte Benutzer beschränken?

Ja, die BlueXP Klassifizierung ist vollständig in BlueXP integriert. BlueXP -Benutzer können nur Informationen zu den Arbeitsumgebungen sehen, die sie gemäß ihren Berechtigungen anzeigen können.

Wenn Sie bestimmten Benutzern erlauben möchten, die BlueXP -Klassifikations-Scanergebnisse einfach anzuzeigen, ohne die Möglichkeit zu haben, die BlueXP -Klassifizierungseinstellungen zu verwalten, können Sie diesen Benutzern die Rolle *Klassifikations-Viewer* zuweisen (bei Verwendung von BlueXP  im Standardmodus) oder die Rolle *Compliance-Viewer* (bei Verwendung von BlueXP  im eingeschränkten Modus). link:concept-cloud-compliance.html["Weitere Informationen ."].



=== Kann jemand auf die privaten Daten zugreifen, die zwischen meinem Browser und der BlueXP Klassifizierung gesendet werden?

Nein Die privaten Daten, die zwischen Ihrem Browser und der BlueXP Klassifizierungsinstanz übertragen werden, sind durch End-to-End-Verschlüsselung mit TLS 1.2 geschützt. Das bedeutet, dass NetApp und andere Anbieter die Daten nicht lesen können. Die BlueXP Klassifizierung gibt keine Daten oder Ergebnisse an NetApp weiter, es sei denn, Sie beantragen und genehmigen den Zugriff.

Die gescannten Daten verbleiben in Ihrer Umgebung.



=== Wie werden sensible Daten behandelt?

NetApp hat keinen Zugriff auf sensible Daten und zeigt sie nicht in der Benutzeroberfläche an. Sensible Daten werden maskiert, beispielsweise werden die letzten vier Zahlen für Kreditkarteninformationen angezeigt.



=== Wo werden die Daten gespeichert?

Die Scan-Ergebnisse werden in Elasticsearch innerhalb der BlueXP Klassifizierungsinstanz gespeichert.



=== Wie wird auf die Daten zugegriffen?

Die BlueXP Klassifizierung greift über API-Aufrufe, die eine Authentifizierung erfordern und mit AES-128 verschlüsselt sind, auf in Elasticsearch gespeicherte Daten zu. Für den direkten Zugriff auf Elasticsearch ist Root-Zugriff erforderlich.



== Lizenzen und Kosten

Die folgende Frage bezieht sich auf Lizenzierung und Kosten der Nutzung der BlueXP Klassifizierung.



=== Wie hoch sind die Kosten für die Klassifizierung von BlueXP?

Die BlueXP Klassifizierung ist eine BlueXP Kernfunktion. Sie ist kostenfrei.



== Connector-Bereitstellung

Die folgenden Fragen beziehen sich auf den BlueXP Connector.



=== Was ist der Steckverbinder?

Der Connector ist eine Software, die auf einer Computing-Instanz entweder in Ihrem Cloud-Konto oder vor Ort ausgeführt wird und es BlueXP ermöglicht, Cloud-Ressourcen sicher zu managen. Sie müssen einen Connector implementieren, um die BlueXP-Klassifizierung zu verwenden.



=== Wo muss der Connector installiert werden?

Beim Scannen von Daten muss der BlueXP -Anschluss an folgenden Stellen installiert werden:

* Für Cloud Volumes ONTAP in AWS oder Amazon FSX für ONTAP: Connector ist in AWS.
* Für Cloud Volumes ONTAP in Azure oder in Azure NetApp Files: Connector ist in Azure.
* Für Cloud Volumes ONTAP in GCP: Connector ist in GCP.
* Bei On-Premises-ONTAP-Systemen: Connector befindet sich vor Ort.


Wenn Sie Daten an diesen Orten haben, müssen Sie möglicherweise verwenden https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["Mehrere Anschlüsse"^].



=== Ist für die BlueXP Klassifizierung Zugriff auf Zugangsdaten erforderlich?

Die BlueXP Klassifizierung selbst ruft keine Storage-Anmeldedaten ab. Stattdessen werden sie im BlueXP Connector gespeichert.

Die BlueXP Klassifizierung verwendet Daten-Ebenen-Anmeldedaten, zum Beispiel CIFS-Zugangsdaten, um Freigaben vor dem Scannen zu mounten.



=== Verwendet die Kommunikation zwischen dem Dienst und dem Connector HTTP?

Ja, die BlueXP Klassifizierung kommuniziert über HTTP mit dem BlueXP Connector.



== Implementierung der BlueXP Klassifizierung

Die folgenden Fragen beziehen sich auf die separate BlueXP Klassifizierungsinstanz.



=== Welche Implementierungsmodelle werden von der BlueXP Klassifizierung unterstützt?

Mit BlueXP können Benutzer Systeme praktisch überall scannen und protokollieren, einschließlich On-Premises-, Cloud- und Hybridumgebungen. Die BlueXP Klassifizierung wird normalerweise mit einem SaaS-Modell implementiert. Bei diesem Modell ist der Service über die BlueXP Schnittstelle aktiviert, sodass keine Hardware- oder Softwareinstallation erforderlich ist. Selbst im Implementierungs-Modus mit einem Klick und einem Klick ist das Datenmanagement möglich, unabhängig davon, ob die Datenspeicher sich vor Ort oder in der Public Cloud befinden.



=== Welche Art von Instanz oder VM ist für die BlueXP Klassifizierung erforderlich?

Wenn link:task-deploy-cloud-compliance.html["In der Cloud implementiert"]:

* In AWS wird die BlueXP Klassifizierung auf einer m6i.4xlarge-Instanz mit einer GP2-Festplatte mit 500 gib ausgeführt. Sie können während der Bereitstellung einen kleineren Instanztyp auswählen.
* In Azure wird die Klassifizierung von BlueXP auf einer Standard_D16s_v3 VM mit einer Festplatte von 500 gib ausgeführt.
* In GCP wird die BlueXP Klassifizierung auf einer VM gemäß n2-Standard-16 mit einer persistenten Standardfestplatte von 500 gib ausgeführt.


link:concept-cloud-compliance.html["Erfahren Sie mehr über die BlueXP Klassifizierung"].



=== Kann ich die BlueXP Klassifizierung auf meinem eigenen Host implementieren?

Ja. Sie können die BlueXP Klassifizierungs-Software auf einem Linux-Host mit Internetzugang in Ihrem Netzwerk oder in der Cloud installieren. Alles funktioniert gleich, und Sie verwalten Ihre Scankonfiguration und -Ergebnisse weiterhin mit BlueXP. Siehe link:task-deploy-compliance-onprem.html["Implementierung der BlueXP Klassifizierung vor Ort"] Für die Systemanforderungen und Installationsdetails.



=== Wie sieht es mit sicheren Websites ohne Internetzugang aus?

Ja, das wird auch unterstützt. Das können Sie link:task-deploy-compliance-dark-site.html["Implementieren Sie die BlueXP Klassifizierung auf einer lokalen Website ohne Internetzugang"] Für vollständig sichere Standorte.
