---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Klassifizierungs-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: Mehr zur BlueXP Klassifizierung
      url: "/concept-cloud-compliance.html"
    - title: Implementieren Sie die BlueXP Klassifizierung
      entries:
      - title: Implementieren Sie mit BlueXP in der Cloud
        url: "/task-deploy-cloud-compliance.html"
      - title: Installation auf einem Linux-Host mit Internetzugang
        url: "/task-deploy-compliance-onprem.html"
      - title: Installation vor Ort ohne Internetzugang
        url: "/task-deploy-compliance-dark-site.html"
      - title: Stellen Sie sicher, dass Ihr Linux Host bereit ist, die BlueXP Klassifizierung
          zu installieren
        url: "/task-test-linux-system.html"
    - title: Aktivieren Sie das Scannen Ihrer Datenquellen
      entries:
      - title: Cloud Volumes ONTAP und On-Premises-ONTAP
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Dateien
        url: "/task-scanning-anf.html"
      - title: Amazon FSX für ONTAP
        url: "/task-scanning-fsx.html"
      - title: Amazon S3 Buckets
        url: "/task-scanning-s3.html"
      - title: Datenbankschemas
        url: "/task-scanning-databases.html"
      - title: OneDrive Accounts
        url: "/task-scanning-onedrive.html"
      - title: SharePoint Konten
        url: "/task-scanning-sharepoint.html"
      - title: Google Drive-Konten
        url: "/task-scanning-google-drive.html"
      - title: Dateifreigaben
        url: "/task-scanning-file-shares.html"
      - title: Objekt-Storage
        url: "/task-scanning-object-storage.html"
    - title: Integrieren Sie Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: Lizenzierung einrichten
      url: "/task-licensing-datasense.html"
    - title: Häufig gestellte Fragen
      url: "/faq-cloud-compliance.html"
  - title: BlueXP Klassifizierung nutzen
    entries:
    - title: Anzeigen von Governance-Details zu Ihren Daten
      url: "/task-controlling-governance-data.html"
    - title: Anzeige von Compliance-Details zu Ihren Daten
      url: "/task-controlling-private-data.html"
    - title: Kategorien von privaten Daten
      url: "/reference-private-data-categories.html"
    - title: Untersuchen Sie Ihre Daten
      url: "/task-investigate-data.html"
    - title: Private Daten organisieren
      url: "/task-org-private-data.html"
    - title: Weisen Sie Daten Richtlinien zu
      url: "/task-using-policies.html"
    - title: Management privater Daten
      url: "/task-managing-highlights.html"
    - title: Überwachen und managen Sie Dateizugriffsereignisse
      url: "/task-manage-file-access-events.html"
    - title: Scaneinstellungen ändern
      url: task-managing-repo-scanning.html
    - title: Erstellen von Compliance-Berichten
      url: "/task-generating-compliance-reports.html"
  - title: BlueXP Klassifizierung managen
    entries:
    - title: Fügen Sie benutzerdefinierte Kennungen für persönliche Daten hinzu
      url: "/task-managing-data-fusion.html"
    - title: Status der BlueXP Klassifizierungsaktionen anzeigen
      url: "/task-view-compliance-actions.html"
    - title: Vorhandene Gruppen-IDs als „für Organisation offen“ definieren
      url: "/task-add-group-id-as-open.html"
    - title: Audit der Historie der BlueXP Klassifizierungsaktionen
      url: "/task-audit-data-sense-actions.html"
    - title: Verringern Sie die Scangeschwindigkeit der BlueXP Klassifizierung
      url: "/task-reduce-scan-speed.html"
    - title: Datenquellen aus der BlueXP Klassifizierung entfernen
      url: "/task-managing-compliance.html"
    - title: Deinstallieren Sie die BlueXP Klassifizierung
      url: "/task-uninstall-data-sense.html"
  - title: Referenz
    entries:
    - title: Unterstützte BlueXP Klassifizierungs-Instanztypen
      url: "/reference-instance-types.html"
    - title: Metadaten, die aus Datenquellen erhoben werden
      url: "/reference-collected-metadata.html"
    - title: Melden Sie sich beim BlueXP Klassifizierungssystem an
      url: "/reference-log-in-to-instance.html"
    - title: BlueXP Klassifizierungs-APIs
      url: "/api-classification.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
