---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP Klassifizierungs-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: Mehr zur BlueXP Klassifizierung
      url: "/concept-cloud-compliance.html"
    - title: Implementieren Sie die BlueXP Klassifizierung
      entries:
      - title: Welche Implementierung sollten Sie verwenden
        url: "/task-deploy-overview.html"
      - title: Implementieren Sie mit BlueXP in der Cloud
        url: "/task-deploy-cloud-compliance.html"
      - title: Installation auf einem Linux-Host mit Internetzugang
        url: "/task-deploy-compliance-onprem.html"
      - title: Installation auf einem lokalen Linux-Host ohne Internetzugang
        url: "/task-deploy-compliance-dark-site.html"
      - title: Stellen Sie sicher, dass Ihr Linux Host bereit ist, die BlueXP Klassifizierung
          zu installieren
        url: "/task-test-linux-system.html"
    - title: Aktivieren Sie das Scannen Ihrer Datenquellen
      entries:
      - title: Überprüfen Sie die Übersicht über Ihre Datenquellen
        url: "/task-scanning-overview.html"
      - title: Azure NetApp Dateien
        url: "/task-scanning-anf.html"
      - title: Amazon FSX für ONTAP
        url: "/task-scanning-fsx.html"
      - title: Cloud Volumes ONTAP und On-Premises-ONTAP
        url: "/task-getting-started-compliance.html"
      - title: Datenbankschemas
        url: "/task-scanning-databases.html"
      - title: Dateifreigaben
        url: "/task-scanning-file-shares.html"
      - title: StorageGRID
        url: "/task-scanning-storagegrid.html"
    - title: Integrieren Sie Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: Häufig gestellte Fragen
      url: "/faq-cloud-compliance.html"
  - title: BlueXP Klassifizierung nutzen
    entries:
    - title: Anzeigen von Governance-Details zu Ihren Daten
      url: "/task-controlling-governance-data.html"
    - title: Anzeige von Compliance-Details zu Ihren Daten
      url: "/task-controlling-private-data.html"
    - title: Kategorien von privaten Daten
      url: "/reference-private-data-categories.html"
    - title: Erstellen Sie einen benutzerdefinierten Scan
      url: "/task-custom-classification.html"
    - title: Untersuchen Sie Ihre Daten
      url: "/task-investigate-data.html"
    - title: Erstellen Sie eine gespeicherte Suche
      url: "/task-using-policies.html"
    - title: Scaneinstellungen ändern
      url: "/task-managing-repo-scanning.html"
    - title: Erstellen von Compliance-Berichten
      url: "/task-generating-compliance-reports.html"
  - title: BlueXP Klassifizierung managen
    entries:
    - title: Verzeichnisse vom Scannen ausschließen
      url: "/task-exclude-scan-paths.html"
    - title: Vorhandene Gruppen-IDs als „für Organisation offen“ definieren
      url: "/task-add-group-id-as-open.html"
    - title: Datenquellen aus der BlueXP Klassifizierung entfernen
      url: "/task-managing-compliance.html"
    - title: Deinstallieren Sie die BlueXP Klassifizierung
      url: "/task-uninstall-data-sense.html"
  - title: Veraltete Funktionen
    entries:
    - title: Liste der veralteten Features
      url: "/reference-free-paid.html"
    - title: Implementieren Sie BlueXP Klassifizierungs-Deprekationen
      entries:
      - title: Installieren Sie die BlueXP Klassifizierung auf mehreren Hosts ohne
          Internetzugang
        url: "/task-deploy-multi-host-install-dark-site.html"
    - title: Datenabschreibungen scannen
      entries:
      - title: Scannen von Amazon S3 Buckets
        url: "/task-scanning-s3.html"
      - title: Scannen Sie OneDrive-Konten
        url: "/task-scanning-onedrive.html"
      - title: Scannen von SharePoint-Konten
        url: "/task-scanning-sharepoint.html"
      - title: Scannen Sie Google Drive-Konten
        url: "/task-scanning-google-drive.html"
      - title: Scannen von Objekt-Storage mithilfe des S3-Protokolls
        url: "/task-scanning-object-storage.html"
    - title: Datenabschreibungen verwalten
      entries:
      - title: Zeigen Sie Governance-Details zu Daten auf dem Governance-Dashboard
          an
        url: "/task-controlling-governance-dashboard-deprecated.html"
      - title: Private Daten organisieren
        url: "/task-org-private-data.html"
      - title: Management privater Daten
        url: "/task-managing-highlights.html"
      - title: Fügen Sie benutzerdefinierte Kennungen für persönliche Daten hinzu
        url: "/task-managing-data-fusion.html"
      - title: Status der BlueXP Klassifizierungsaktionen anzeigen
        url: "/task-view-compliance-actions.html"
      - title: Audit der Historie der BlueXP Klassifizierungsaktionen
        url: "/task-audit-data-sense-actions.html"
      - title: Verringern Sie die Scangeschwindigkeit der BlueXP Klassifizierung
        url: "/task-reduce-scan-speed.html"
      - title: Entfernen Sie ein OneDrive-, SharePoint- oder Google Drive-Konto
        url: "/task-managing-compliance-deprecated.html"
  - title: Referenz
    entries:
    - title: Unterstützte BlueXP Klassifizierungs-Instanztypen
      url: "/reference-instance-types.html"
    - title: Metadaten, die aus Datenquellen erhoben werden
      url: "/reference-collected-metadata.html"
    - title: Melden Sie sich beim BlueXP Klassifizierungssystem an
      url: "/reference-log-in-to-instance.html"
    - title: BlueXP Klassifizierungs-APIs
      url: "/api-classification.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
