---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: Die BlueXP Klassifizierungssoftware muss auf einem Host ausgeführt werden, der bestimmte Betriebssystemanforderungen, RAM-Anforderungen, Software-Anforderungen usw. erfüllt. Bei der Implementierung der BlueXP Klassifizierung in der Cloud empfehlen wir, ein System mit den „großen“ Merkmalen zu verwenden, um den vollen Funktionsumfang zu erhalten. 
---
= Unterstützte BlueXP Klassifizierungs-Instanztypen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die BlueXP Klassifizierungssoftware muss auf einem Host ausgeführt werden, der bestimmte Betriebssystemanforderungen, RAM-Anforderungen, Software-Anforderungen usw. erfüllt. Bei der Implementierung der BlueXP Klassifizierung in der Cloud empfehlen wir, ein System mit den „großen“ Merkmalen zu verwenden, um den vollen Funktionsumfang zu erhalten.

Sie können die BlueXP Klassifizierung auf einem System mit weniger CPUs und weniger RAM implementieren. Bei der Nutzung dieser weniger leistungsstarken Systeme bestehen jedoch einige Einschränkungen. link:concept-cloud-compliance.html["Informieren Sie sich über diese Einschränkungen"^].

Wenn in den folgenden Tabellen das als „Standard“ markierte System in der Region, in der Sie die BlueXP-Klassifizierung installieren, nicht verfügbar ist, wird das nächste System in der Tabelle bereitgestellt.



== AWS-Instanztypen

[cols="20,30,25"]
|===
| Systemgröße | Spezifikationen | Instanztyp 


| Extra Groß | 32 CPUs, 128 GB RAM, 1 tib gp3-SSD | https://aws.amazon.com/ec2/instance-types/m6i/["M6i.8xlarge"^] (Standard) 


| Groß | 16 CPUs, 64 GB RAM, 500 gib SSD | https://aws.amazon.com/ec2/instance-types/m6i/["M6i.4xlarge"^] (Standard) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 


| Mittel | 8 CPUs, 32 GB RAM, 200 gib SSD | https://aws.amazon.com/ec2/instance-types/m6i/["M6i.2xlarge"^] (Standard) m6a.2xlarge m5a.2xlarge m5.2xlarge m4.2xlarge 


| Klein | 8 CPUs, 16 GB RAM, 100 gib SSD | https://aws.amazon.com/ec2/instance-types/c6a/["c6a.2xlarge"^] (Standard) c5a.2xlarge c5.2xlarge c4.2xlarge 
|===


== Azure Instanztypen

[cols="20,30,25"]
|===
| Systemgröße | Spezifikationen | Instanztyp 


| Extra Groß | 32 CPUs, 128 GB RAM, BS-Festplatte (2,048 gib, min. 250 MB/s Durchsatz) und Datenfestplatte (1 tib SSD, min. 750 MB/s Durchsatz) | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dv3-series["Standard_D32_v3"^] (Standard) 


| Groß | 16 CPUs, 64 GB RAM, 500 gib SSD | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^] (Standard) 
|===


== GCP-Instanztypen

[cols="20,30,25"]
|===
| Systemgröße | Spezifikationen | Instanztyp 


| Groß | 16 CPUs, 64 GB RAM, 500 gib SSD | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-Standard-16"^] (Standard) n2d-Standard-16 n1-Standard-16 
|===