---
sidebar: sidebar 
permalink: task-custom-classification.html 
keywords: custom classification, customize, regular expression, keyword, regex 
summary: Mit der BlueXP -Klassifizierung können Sie die Suche nach vertraulichen Informationen anpassen und den Service an individuelle Muster und Schlüsselwörter anpassen, die für Ihr Unternehmen relevant sind. 
---
= Erstellen Sie eine benutzerdefinierte Klassifizierung in der BlueXP -Klassifizierung
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit der BlueXP -Klassifizierung können Sie eine benutzerdefinierte Suche nach sensiblen Informationen erstellen. Die Suche kann auf einen regulären Ausdruck oder eine Reihe von Schlüsselwörtern für die Nähe festgelegt werden.



== Erstellen Sie eine benutzerdefinierte Klassifizierung

Benutzerdefinierte Klassifizierung ist nur für Karten- und Klassifikations-Scans verfügbar, nicht für nur-Mapping-Scans. Diese Funktion befindet sich derzeit in der Vorschau.

.Schritte
. Wählen Sie die Registerkarte **Benutzerdefinierte Klassifizierung**.
. Wählen Sie den **Neuen Klassifikator hinzufügen**.
. Fügen Sie Namen und Beschreibung für den neuen Klassifikator hinzu.
. Um die Anpassung als regulärer Ausdruck hinzuzufügen, wählen Sie **Benutzerdefinierter regulärer Ausdruck** und dann **Weiter**.
+
.. Fügen Sie für einen regulären Ausdruck das Muster hinzu, um die spezifischen Informationen Ihrer Daten zu erkennen. Zum Beispiel wäre die 12-stellige ID, die mit 201 beginnt, \b201\f\d(9)B. Wählen Sie **Validieren**, um die Syntax Ihres Eintrags zu bestätigen.




Die neue Anpassung wird beim nächsten geplanten Scan erfasst. Informationen zum Anzeigen der Ergebnisse finden Sie unter xref:task-generating-compliance-reports.html[Erstellen von Compliance-Berichten].
