---
sidebar: sidebar 
permalink: task-deploy-multi-host-install-dark-site.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, web browser connectivity, cloud compliance access, privacy, compliance, on-premises, dark site, upgrade, private mode, docker, podman, bluexp classification, classification, install 
summary: Führen Sie einige Schritte aus, um die BlueXP Klassifizierung auf einem Linux-Host auf einer lokalen Site ohne Internetzugang – auch als „privater Modus“ bezeichnet – zu installieren. Diese Art der Installation ist perfekt für Ihre sicheren Standorte. 
---
= Installieren Sie die BlueXP Klassifizierung auf mehreren Hosts für große Konfigurationen ohne Internetzugang
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Führen Sie ein paar Schritte aus, um die BlueXP Klassifizierung auf mehreren Hosts an einem lokalen Standort ohne Internetzugang zu installieren – auch als „_Private Mode_“ bekannt. Diese Art der Installation ist perfekt für Ihre sicheren Standorte.

Bei sehr großen Konfigurationen, bei denen an Standorten ohne Internetzugang Datenmengen im Petabyte-Bereich gescannt werden sollen, können Sie mehrere Hosts einschließen, um zusätzliche Verarbeitungsleistung bereitzustellen. Bei der Verwendung mehrerer Hostsysteme wird das primäre System als _Manager-Node_ bezeichnet, und die zusätzlichen Systeme, die zusätzliche Rechenleistung bieten, heißen _Scanner-Nodes_.

Befolgen Sie diese Schritte, wenn Sie die BlueXP Klassifizierungssoftware auf mehreren lokalen Hosts in einer Offline-Umgebung installieren.

[]
====
*HINWEIS* Diese Informationen sind nur für die BlueXP-Klassifikation der älteren Versionen 1.30 und früher relevant.

====
.Was Sie benötigen
* Überprüfen Sie, ob alle Linux-Systeme für die Knoten Manager und Scanner die Host-Anforderungen erfüllen.
* Überprüfen Sie, ob Sie die beiden erforderlichen Softwarepakete (Docker Engine oder Podman und Python 3) installiert haben.
* Stellen Sie sicher, dass Sie auf den Linux-Systemen über Root-Rechte verfügen.
* Stellen Sie sicher, dass Ihre Offline-Umgebung die erforderlichen Berechtigungen und Konnektivität erfüllt.
* Sie müssen über die IP-Adressen der zu verwendenden Scanner-Knoten-Hosts verfügen.
* Die folgenden Ports und Protokolle müssen auf allen Hosts aktiviert sein:
+
[cols="15,20,55"]
|===
| Port | Protokolle | Beschreibung 


| 2377 | TCP | Cluster-Management-Kommunikation 


| 7946 | TCP, UDP | Kommunikation zwischen den Knoten 


| 4789 | UDP | Overlay-Netzwerk-Traffic 


| 50 | ESP | Verschlüsselter ESP-Datenverkehr (IPsec Overlay Network) 


| 111 | TCP, UDP | NFS-Server für die gemeinsame Nutzung von Dateien zwischen den Hosts (benötigt von jedem Scanner-Knoten zu Manager-Knoten) 


| 2049 | TCP, UDP | NFS-Server für die gemeinsame Nutzung von Dateien zwischen den Hosts (benötigt von jedem Scanner-Knoten zu Manager-Knoten) 
|===


.Schritte
. Befolgen Sie die Schritte 1 bis 8 vom link:task-deploy-compliance-dark-site.html#single-host-installation-for-typical-configurations["Installation über einen Host"] Auf dem Knoten Manager.
. Wie in Schritt 9 gezeigt, können Sie bei Aufforderung durch das Installationsprogramm die erforderlichen Werte in eine Reihe von Eingabeaufforderungen eingeben oder die erforderlichen Parameter als Befehlszeilenargumente für das Installationsprogramm bereitstellen.
+
Zusätzlich zu den Variablen, die für eine Installation mit einem Host verfügbar sind, wird eine neue Option *-n <Node_ip>* verwendet, um die IP-Adressen der Scannerknoten anzugeben. Mehrere Knoten-IPs werden durch Komma getrennt.

+
Mit diesem Befehl werden beispielsweise 3 Scannerknoten hinzugefügt:
`sudo ./install.sh -a <account_id> -c <client_id> -t <user_token> --host <ds_host> --manager-host <cm_host> *-n <node_ip1>,<node_ip2>,<node_ip3>* --no-proxy --darksite`

. Bevor die Installation des Manager-Node abgeschlossen ist, wird in einem Dialogfeld der für die Scanner-Knoten erforderliche Installationsbefehl angezeigt. Kopieren Sie den Befehl (z. B.: `sudo ./node_install.sh -m 10.11.12.13 -t ABCDEF-1-3u69m1-1s35212`) Und in einer Textdatei speichern.
. Auf * jedem Scanner-Knoten-Host:
+
.. Kopieren Sie die Data Sense Installer-Datei (*cc_onprem_Installer.tar.gz*) auf den Host-Rechner.
.. Entpacken Sie die Installationsdatei.
.. Fügen Sie den Befehl ein, den Sie in Schritt 3 kopiert haben, und führen Sie ihn aus.
+
Wenn die Installation auf allen Scanner-Knoten abgeschlossen ist und sie mit dem Manager-Knoten verbunden wurden, wird auch die Installation des Manager-Knotens abgeschlossen.





.Ergebnis
Das BlueXP Klassifizierungs-Installationsprogramm schließt die Installation der Pakete ab und registriert die Installation. Die Installation dauert 15 bis 25 Minuten.

.Nächste Schritte
Auf der Konfigurationsseite können Sie das lokale auswählen link:task-getting-started-compliance.html["ONTAP-Cluster vor Ort"] Und lokal link:task-scanning-databases.html["Datenbanken"] Die Sie scannen möchten.
