---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Erfahren Sie mehr über die Neuerungen bei der BlueXP Klassifizierung. 
---
= Neuerungen bei der BlueXP Klassifizierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen bei der BlueXP Klassifizierung.



== 3. April 2023 (Version 1.22)



=== Neuer Data Discovery Assessment Report

Der Data Discovery Assessment Report bietet eine allgemeine Analyse Ihrer gescannten Umgebung, um die Ergebnisse des Systems hervorzuheben und Problembereiche und mögliche Schritte zur Problembehebung aufzuzeigen. Ziel dieses Berichts ist es, ein Bewusstsein für Bedenken im Zusammenhang mit der Data Governance, Schwachstellen bei der Datensicherheit und Lücken in der Daten-Compliance in Ihrem Datensatz zu schaffen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-discovery-assessment-report["Erfahren Sie, wie Sie den Data Discovery Assessment Report erstellen und verwenden"].



=== Möglichkeit zur Implementierung der BlueXP Klassifizierung auf kleineren Instanzen in der Cloud

Bei der Implementierung der BlueXP Klassifizierung aus einem BlueXP Connector in einer AWS-Umgebung können Sie nun zwischen zwei kleineren Instanztypen wählen als bei der Standardinstanz. Wenn Sie eine kleine Umgebung scannen, können Sie hier Cloud-Kosten sparen. Allerdings gibt es einige Einschränkungen bei der Verwendung der kleineren Instanz. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html#using-a-smaller-instance-type["Anzeigen der verfügbaren Instanztypen und Einschränkungen"].



=== Eigenständiges Skript steht jetzt zur Verfügung, um Ihr Linux-System vor der Installation der BlueXP Klassifizierung zu qualifizieren

Wenn Sie unabhängig von der Ausführung der BlueXP Klassifizierungssysteminstallation überprüfen möchten, ob Ihr Linux-System alle Voraussetzungen erfüllt, steht Ihnen ein separates Skript zur Verfügung, das nur die Voraussetzungen testet. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-test-linux-system.html["Erfahren Sie, wie Sie überprüfen können, ob Ihr Linux-Host bereit ist, die BlueXP Klassifizierung zu installieren"].



== 7. März 2023 (Version 1.21)



=== Neue Funktionen, mit denen Sie Ihre eigenen benutzerdefinierten Kategorien von der BlueXP Klassifizierungs-UI hinzufügen können

Mit der BlueXP Klassifizierung können Sie jetzt Ihre eigenen benutzerdefinierten Kategorien hinzufügen, sodass die Dateien nach der BlueXP Klassifizierung ermittelt werden, die zu diesen Kategorien passen. Die BlueXP Klassifizierung hat viele https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories["Vordefinierte Kategorien"]Diese Funktion ermöglicht es Ihnen, benutzerdefinierte Kategorien hinzuzufügen, um zu ermitteln, wo Informationen, die für Ihre Organisation einzigartig sind, in Ihren Daten gefunden werden.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories["Weitere Informationen ."^].



=== Sie können jetzt benutzerdefinierte Schlüsselwörter aus der BlueXP Klassifizierungs-UI hinzufügen

Mit der BlueXP Klassifizierung konnten benutzerdefinierte Schlüsselwörter hinzugefügt werden, die durch die BlueXP Klassifizierung bei zukünftigen Scans ab und an identifiziert werden. Sie mussten sich jedoch beim BlueXP Klassifizierungs-Linux-Host anmelden und eine Befehlszeilenschnittstelle verwenden, um die Schlüsselwörter hinzuzufügen. In dieser Version können benutzerdefinierte Schlüsselwörter in der BlueXP Klassifizierungs-UI hinzugefügt werden. Dies macht es sehr einfach, diese Schlüsselwörter hinzuzufügen und zu bearbeiten.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Weitere Informationen zum Hinzufügen benutzerdefinierter Schlüsselwörter finden Sie in der BlueXP Klassifizierungs-UI"^].



=== Möglichkeit zur BlueXP Klassifizierung *nicht* von Dateien, wenn die „Uhrzeit des letzten Zugriffs“ geändert wird

Wenn die BlueXP Klassifizierung keine ausreichenden „Schreib“-Berechtigungen besitzt, scannt das System standardmäßig keine Dateien in Ihren Volumes, da die BlueXP Klassifizierung die „letzte Zugriffszeit“ nicht auf den ursprünglichen Zeitstempel zurücksetzen kann. Wenn es Ihnen jedoch egal ist, ob die letzte Zugriffszeit in Ihren Dateien auf die ursprüngliche Uhrzeit zurückgesetzt wird, können Sie dieses Verhalten auf der Konfigurationsseite außer Kraft setzen, damit die BlueXP Klassifizierung die Volumes unabhängig von den Berechtigungen scannt.

In Verbindung mit dieser Funktion steht nun ein neuer Filter namens „Scan Analysis Event“ zur Verfügung, mit dem Sie die Dateien anzeigen können, die nicht klassifiziert wurden, weil die BlueXP Klassifizierung den Zeitpunkt des letzten Zugriffs nicht rückgängig machen konnte, oder die Dateien, die klassifiziert wurden, obwohl die BlueXP Klassifizierung beim letzten Zugriff nicht rückgängig gemacht wurde.

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp["Erfahren Sie mehr über den „Zeitstempel des letzten Zugriffs“ und die Berechtigungen, die die BlueXP Klassifizierung erfordert"].



=== Drei neue Arten von personenbezogenen Daten werden durch die BlueXP Klassifizierung identifiziert

Mit der BlueXP Klassifizierung können Dateien identifiziert und kategorisiert werden, die die folgenden Datentypen enthalten:

* Botswana Identity Card (Omang)-Nummer
* Botswana Passnummer
* Personalausweis für die nationale Registrierung in Singapur (NRIC)


https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Hier können Sie alle Arten von personenbezogenen Daten einsehen, die durch die BlueXP Klassifizierung in Ihren Daten identifiziert werden können"].



=== Aktualisierte Funktionalität für Verzeichnisse

* Die Option „leichter CSV-Bericht“ für Datenuntersuchungsberichte enthält jetzt Informationen aus Verzeichnissen.
* Der Zeitfilter „Letzter Zugriff“ zeigt jetzt die zuletzt verwendete Zeit für Dateien und Verzeichnisse an.




=== Installationsverbesserungen führen zu

* Die BlueXP Klassifizierung kann auf Linux-Hosts mit CentOS Stream 8 installiert werden.
* Der BlueXP Klassifizierungs-Installer für Standorte ohne Internetzugang (Dark Sites) führt jetzt eine Vorabprüfung durch, um sicherzustellen, dass Ihre System- und Netzwerkanforderungen für eine erfolgreiche Installation bestehen.
* Die Protokolldateien der Installationsaudits werden jetzt gespeichert und in geschrieben `/ops/netapp/install_logs`.




== 5. Februar 2023 (Version 1.20)



=== Möglichkeit, Policy-basierte Benachrichtigungs-E-Mails an jede beliebige E-Mail-Adresse zu senden

In früheren Versionen der BlueXP Klassifizierung können Sie E-Mail-Benachrichtigungen an die BlueXP Benutzer Ihres Kontos senden, wenn bestimmte kritische Richtlinien Ergebnisse liefern. Mit dieser Funktion erhalten Sie Benachrichtigungen zum Schutz Ihrer Daten, wenn Sie nicht online sind. Jetzt können Sie auch E-Mail-Benachrichtigungen von Policies an andere Benutzer senden - bis zu 20 E-Mail-Adressen - die nicht in Ihrem BlueXP-Konto sind.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["Erfahren Sie mehr über das Senden von E-Mail-Benachrichtigungen basierend auf Policy-Ergebnissen"].



=== Sie können jetzt persönliche Muster über die BlueXP Klassifizierungs-UI hinzufügen

Mit der BlueXP Klassifizierung konnten individuelle „persönliche Daten“ hinzugefügt werden, die durch die BlueXP Klassifizierung in künftigen Scans schon seit einiger Zeit erkannt werden. Sie mussten sich jedoch beim BlueXP Klassifizierungs-Linux-Host anmelden und eine Befehlszeile verwenden, um die benutzerdefinierten Muster hinzuzufügen. In dieser Version besteht die Möglichkeit, persönliche Muster mit einem regex hinzuzufügen, indem sie die BlueXP Klassifizierungs-UI verwenden. Damit ist es sehr einfach, diese benutzerdefinierten Muster hinzuzufügen und zu bearbeiten.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Weitere Informationen zum Hinzufügen benutzerdefinierter Muster erhalten Sie über die BlueXP Klassifizierungs-UI"^].



=== Möglichkeit zum Verschieben von 15 Millionen Dateien mithilfe der BlueXP Klassifizierung

In der Vergangenheit können Sie durch die BlueXP Klassifizierung maximal 100,000 Quelldateien auf eine beliebige NFS-Freigabe verschieben. Sie können jetzt bis zu 15 Millionen Dateien gleichzeitig verschieben. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Weitere Informationen zum Verschieben von Quelldateien mithilfe der BlueXP Klassifizierung"].



=== Fähigkeit, die Anzahl der Benutzer zu sehen, die Zugriff auf SharePoint Online-Dateien haben

Der Filter "Anzahl der Benutzer mit Zugriff" unterstützt nun Dateien, die in SharePoint Online-Repositorys gespeichert sind. In der Vergangenheit wurden nur Dateien auf CIFS Shares unterstützt. Beachten Sie, dass SharePoint-Gruppen, die nicht auf Active Directory basieren, derzeit nicht in diesen Filter gezählt werden.



=== Der Aktionsstatus wurde um einen neuen Status „Teilerfolg“ erweitert

Der neue Status „Teilsuccess“ zeigt an, dass eine BlueXP-Klassifizierungsaktion abgeschlossen ist und einige Elemente fehlgeschlagen sind und einige Elemente erfolgreich waren, z. B. wenn Sie 100 Dateien verschieben oder löschen. Außerdem wurde der Status „Fertig“ in „Erfolg“ umbenannt. In der Vergangenheit können im Status „Fertig“ Aktionen aufgeführt werden, die erfolgreich waren und die fehlgeschlagen sind. Der Status „Erfolg“ bedeutet nun, dass alle Aktionen erfolgreich auf allen Elementen durchgeführt wurden. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html["Lesen Sie, wie Sie das Fenster „Aktionsstatus“ anzeigen"].



== 9. Januar 2023 (Version 1.19)



=== Möglichkeit, ein Diagramm von Dateien anzuzeigen, die sensible Daten enthalten und die übermäßig permissiv sind

Das Governance Dashboard hat einen neuen Bereich mit „_sensitiven Daten“ und „Wide Permissions_“ hinzugefügt, der eine Heatmap mit Dateien enthält, die vertrauliche Daten (einschließlich sensibler und sensibler personenbezogener Daten) enthalten und die zu permissiv sind. So erkennen Sie, wo Sie möglicherweise Risiken mit sensiblen Daten haben. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Weitere Informationen ."].



=== Auf der Seite „Datenuntersuchung“ stehen drei neue Filter zur Verfügung

Es stehen neue Filter zur Verfügung, um die Ergebnisse zu verfeinern, die auf der Seite „Datenuntersuchung“ angezeigt werden:

* Der Filter „Anzahl der Benutzer mit Zugriff“ zeigt an, welche Dateien und Ordner für eine bestimmte Anzahl von Benutzern geöffnet sind. Sie können einen Zahlenbereich auswählen, um die Ergebnisse zu verfeinern, z. B. um zu sehen, auf welche Dateien 51-100 Benutzer zugreifen können.
* Mit den Filtern „erstellte Zeit“, „entdeckte Zeit“, „Zuletzt geändert“ und „Letzter Zugriff“ können Sie jetzt einen benutzerdefinierten Datumsbereich erstellen, anstatt nur einen vordefinierten Zeitraum von Tagen auszuwählen. Sie können beispielsweise nach Dateien mit einer "Erstellungszeit" "älter als 6 Monate" oder mit einem "Letzter geändert" Datum innerhalb der "letzten 10 Tage" suchen.
* Mit dem Filter „Dateipfad“ können Sie nun Pfade festlegen, die Sie aus den gefilterten Abfrageergebnissen ausschließen möchten. Wenn Sie Pfade zum ein- und Ausschließen bestimmter Daten eingeben, findet die BlueXP Klassifizierung zuerst alle Dateien in den eingeschlossenen Pfaden, dann entfernt sie Dateien aus ausgeschlossenen Pfaden und zeigt dann die Ergebnisse an.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page["Sehen Sie sich die Liste aller Filter an, mit denen Sie Ihre Daten untersuchen können"].



=== Durch die BlueXP Klassifizierung kann die japanische individuelle Nummer identifiziert werden

Durch die BlueXP Klassifizierung können Dateien identifiziert und kategorisiert werden, die die japanische individuelle Nummer (auch „Meine Nummer“) enthalten. Dazu gehört sowohl die persönliche als auch die Firmennummer. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Hier können Sie alle Arten von personenbezogenen Daten einsehen, die durch die BlueXP Klassifizierung in Ihren Daten identifiziert werden können"].



== 11. Dezember 2022 (Version 1.18)



=== Erweiterungen für die Installation vor Ort

Die folgenden Erweiterungen wurden für die On-Prem Data Sense Installation hinzugefügt:

* Einige zusätzliche Voraussetzungen werden jetzt geprüft, bevor die Installation auf einem lokalen Host gestartet wird. Dadurch kann sichergestellt werden, dass Ihr Hostsystem zu 100 % bereit ist, wenn Daten Sense Software installiert wird:
+
** Testen Sie ausreichend Speicherplatz auf `/var/lib/docker`, `/tmp`, und `/opt`
** Testen Sie die entsprechenden Berechtigungen für alle erforderlichen Ordner


* Auf der Seite Konfiguration zeigt jetzt der Abschnitt Arbeitsumgebungen die ID _Arbeitsumgebung_ und den Namen _Scannergruppe_ an. Wenn Sie mehrere Data Sense Hosts verwenden möchten, um zusätzliche Verarbeitungsleistung für das Scannen Ihrer Datenquellen bereitzustellen, müssen Sie die ID der Arbeitsumgebung kennen.
* Außerdem zeigt ein neuer Abschnitt auf der Konfigurationsseite die Scannergruppen, die Sie eingerichtet haben, und die Scannerknoten, die sich in jeder Gruppe befinden.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["Erfahren Sie mehr über die Installation von Data Sense auf einem einzelnen Host-Server und auf mehreren Hosts"].



== 13. November 2022 (Version 1.17)



=== Unterstützung für das Scannen von On-Premises-Konten von SharePoint

Data Sense kann jetzt sowohl SharePoint Online-Konten als auch SharePoint On-Premises-Konten (SharePoint Server) scannen. Wenn Sie SharePoint auf Ihren eigenen Servern oder auf Websites ohne Internetzugang installieren müssen, können Sie jetzt Data Sense die Benutzerdateien in diesen Konten scannen lassen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["Weitere Informationen ."^].



=== Möglichkeit zum erneuten Scannen mehrerer Verzeichnisse (Ordner oder Freigaben)

Jetzt können Sie mehrere Verzeichnisse (Ordner oder Freigaben) sofort erneut scannen, sodass Änderungen im System berücksichtigt werden. So können Sie das erneute Scannen bestimmter Daten vor anderen Daten priorisieren. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Lesen Sie, wie Sie ein Verzeichnis erneut scannen"^].



=== Möglichkeit zum Hinzufügen weiterer „Scanner“-Knoten vor Ort, um bestimmte Datenquellen zu scannen

Wenn Sie Data Sense an einem lokalen Standort installiert haben und feststellen, dass Sie mehr Scanning Processing Power zum Scannen bestimmter Datenquellen benötigen, können Sie weitere „Scanner“-Knoten hinzufügen und diese zum Scannen dieser Datenquellen zuordnen. Sie können die Scanner-Knoten unmittelbar nach der Installation des Manager-Knotens hinzufügen oder später einen Scanner-Knoten hinzufügen.

Bei Bedarf können die Scanner-Knoten auf Hostsystemen installiert werden, die sich physisch näher an den zu scannenden Datenquellen befinden. Je näher der Scanner-Knoten an den Daten liegt, desto besser, da er die Netzwerklatenz so weit wie möglich beim Scannen der Daten reduziert. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["Lesen Sie, wie Scannerknoten installiert werden, um zusätzliche Datenquellen zu scannen"^].



=== Vor dem Start der Installation führen die vor-Ort-Installationsprogramme nun eine Vorprüfung durch

Bei der Installation von Data Sense auf einem Linux-System überprüft der Installer, ob das System alle erforderlichen Anforderungen (CPU, RAM, Kapazität, Netzwerk usw.) erfüllt, bevor die eigentliche Installation gestartet wird. Dies hilft beim Auffangen von Problemen *vor* verbringen Sie Zeit mit der Installation.



== 6. September 2022 (Version 1.16)



=== Fähigkeit, ein Repository sofort erneut zu scannen, um Änderungen in Dateien widerzuspiegeln

Wenn Sie ein bestimmtes Repository sofort erneut scannen müssen, damit Änderungen im System angezeigt werden, können Sie das Repository auswählen und erneut scannen. So können Sie das erneute Scannen bestimmter Daten vor anderen Daten priorisieren. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Lesen Sie, wie Sie ein Verzeichnis erneut scannen"^].



=== Neuer Filter für den Status der Datensense-Suche auf der Seite Datenuntersuchung

Mit dem Filter „Analysestatus“ können Sie die Dateien auflisten, die sich in einer bestimmten Phase des Datensense-Scans befinden. Sie können eine Option auswählen, um die Liste der Dateien anzuzeigen, die *ausstehender erster Scan*, *Abgeschlossen* gescannt werden, *ausstehender Rescan* oder die *nicht erfolgreich* gescannt werden müssen.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Sehen Sie sich die Liste aller Filter an, mit denen Sie Ihre Daten untersuchen können"^].



=== Die Betroffenen werden nun als Teil von "personenbezogenen Daten" in Scans gefunden

Data Sense erkennt nun Betroffenen als Teil der im Compliance Dashboard angezeigten persönlichen Ergebnisse. Darüber hinaus können Sie bei einer Suche auf der Untersuchungsseite unter „personenbezogene Daten“ „Betroffene“ auswählen, um nur Dateien anzuzeigen, die betroffene Personen enthalten.



=== Datensense-Breadcrumb-Dateien werden jetzt als Teil von "Kategorien" in Scans gefunden betrachtet

Data Sense erkennt jetzt Breadcrumb-Dateien als Teil der Kategorien, die im Compliance Dashboard angezeigt werden. Dies sind Dateien, die Data Sense beim Verschieben von Dateien vom Quellspeicherort in eine NFS-Freigabe erstellt. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Erfahren Sie mehr darüber, wie Breadcrumb-Dateien erstellt werden"^].

Wenn Sie eine Suche auf der Untersuchungsseite durchführen, können Sie unter „Kategorie“ „Datensense Breadcrumbs“ „Data Sense Breadcrumb“ auswählen, um nur Daten Sense Breadcrumb-Dateien anzuzeigen.



== 7. August 2022 (Version 1.15)



=== Fünf neue Arten von personenbezogenen Daten aus Neuseeland werden durch Data Sense identifiziert

Data Sense kann Dateien identifizieren und kategorisieren, die die folgenden Datentypen enthalten:

* Kontonummer Der Neuseeländischen Bank
* Führerschein für Neuseeland
* Neuseeland-IRD-Nummer (Steuernummer)
* Neuseeland NHI (National Health Index) Nummer
* Neuseeländische Passnummer


link:reference-private-data-categories.html#types-of-personal-data["Sehen Sie alle Arten von personenbezogenen Daten an, die Data Sense in Ihren Daten identifizieren kann"].



=== Möglichkeit, eine Breadcrumb-Datei hinzuzufügen, um anzugeben, warum eine Datei verschoben wurde

Wenn Sie die Funktion „Data Sense“ verwenden, um Quelldateien in eine NFS-Freigabe zu verschieben, können Sie nun eine Breadcrumb-Datei an dem Speicherort der verschobenen Datei belassen. Eine Breadcrumb-Datei hilft Ihren Benutzern zu verstehen, warum eine Datei vom ursprünglichen Speicherort verschoben wurde. Für jede verschobene Datei erstellt das System eine Breadcrumb-Datei im Quellspeicherort mit dem Namen `<filename>-breadcrumb-<date>.txt` Um den Speicherort anzuzeigen, an dem die Datei verschoben wurde, und den Benutzer, der die Datei verschoben hat. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Weitere Informationen ."^].



=== Personenbezogene Daten und sensible personenbezogene Daten in Ihren Verzeichnissen werden in Untersuchungsergebnissen angezeigt

Auf der Seite „Datenuntersuchung“ werden nun Ergebnisse für persönliche Daten und sensible personenbezogene Daten in Ihren Verzeichnissen (Ordner und Freigaben) angezeigt. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["Hier sehen Sie ein Beispiel"^].



=== Zeigen Sie den Status an, wie viele Volumes, Buckets usw. erfolgreich klassifiziert wurden

Wenn Sie sich die einzelnen Repositorys ansehen, die Data Sense verwenden (Volumes, Buckets usw.), sehen Sie jetzt, wie viele Daten gescannt wurden und wie viele als „klassifiziert“ wurden. Die Klassifizierung dauert länger, wenn für alle Daten die vollständige KI-Identifizierung durchgeführt wird. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["Lesen Sie, wie Sie diese Informationen anzeigen"^].



=== Jetzt können Sie benutzerdefinierte Muster hinzufügen, die Data Sense in Ihren Daten identifiziert

Es gibt zwei Möglichkeiten, wie Sie benutzerdefinierte "persönliche Daten" hinzufügen können, die Data Sense in zukünftigen Scans identifizieren wird. So haben Sie einen vollständigen Überblick darüber, wo sich potenziell sensible Daten in den Dateien Ihres Unternehmens befinden.

* Sie können benutzerdefinierte Schlüsselwörter aus einer Textdatei hinzufügen.
* Sie können ein persönliches Muster mit einem regulären Ausdruck (regex) hinzufügen.


Diese Schlüsselwörter und Muster werden den bereits vorhandenen vordefinierten Mustern hinzugefügt, die Data Sense verwendet. Die Ergebnisse werden im Abschnitt Persönliche Muster angezeigt. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["Weitere Informationen ."^].



== 6. Juli 2022 (Version 1.14)



=== Jetzt können Sie die Benutzer und Gruppen anzeigen, die Zugriff auf Ihre Verzeichnisse haben

In der Vergangenheit können Sie die Arten von offenen Berechtigungen anzeigen, die für einzelne Dateien gewährt wurden. Jetzt können Sie eine Liste aller Benutzer oder Gruppen anzeigen, die Zugriff auf Verzeichnisse (Ordner und Dateifreigaben) haben, und die Arten von Berechtigungen, die sie haben. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["Lesen Sie, wie Sie die Benutzer und Gruppen anzeigen, die Zugriff auf Ihre Ordner und Dateifreigaben haben"].



=== Sie können das Scannen eines Repository anhalten, um vorübergehend das Scannen bestimmter Inhalte zu beenden

Wenn Sie das Scannen anhalten, führt Data Sense keinen zukünftigen Scan auf beliebigen Ergänzungen oder Änderungen an einem Volume oder Bucket durch, aber alle aktuellen Ergebnisse sind weiterhin im System verfügbar. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["Erfahren Sie, wie Sie den Scanvorgang anhalten und fortsetzen"].



=== DIE Lizenzdaten DES US-Fahrers aus drei weiteren Staaten können durch Data Sense identifiziert werden

Data Sense kann Dateien identifizieren und kategorisieren, die die Lizenzdaten von Treibern aus Indiana, New York und Texas enthalten. link:reference-private-data-categories.html#types-of-personal-data["Sehen Sie alle Arten von personenbezogenen Daten an, die Data Sense in Ihren Daten identifizieren kann"].



=== Richtlinien geben nun Verzeichnisse zurück, die den Suchkriterien entsprechen

In der Vergangenheit, als Sie eine benutzerdefinierte Richtlinie erstellt haben, wurden die Dateien angezeigt, die den Suchkriterien entsprechen. Nun werden in den Ergebnissen auch die Verzeichnisse (Ordner und Dateifreigaben) angezeigt, die der Abfrage entsprechen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["Weitere Informationen zum Erstellen von Richtlinien"].



=== „Data Sense“ kann jetzt bis zu 100,000 Dateien auf einmal verschieben

Wenn Sie „Data Sense“ zum Verschieben von Dateien von einer gescannten Datenquelle in eine NFS-Freigabe verwenden möchten, wurde die maximale Anzahl von Dateien auf 100,000 Dateien erhöht. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Erfahren Sie, wie Sie Dateien mit Data Sense verschieben"].



== 12. Juni 2022 (Version 1.13.1)



=== Jetzt können Sie die Ergebnisse von der Seite Datenuntersuchung als JSON-Bericht herunterladen

Nachdem Sie die Daten auf der Seite „Datenuntersuchung“ gefiltert haben, können Sie die Daten nun als Bericht in einer JSON-Datei speichern, die Sie in eine NFS-Freigabe exportieren können, und die Daten zusätzlich in eine .CSV-Datei auf Ihrem lokalen System speichern. Stellen Sie sicher, dass Data Sense über die richtigen Berechtigungen für den Exportzugriff verfügt. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["Lesen Sie, wie Berichte von der Seite „Datenuntersuchung“ erstellt werden"].



=== Fähigkeit zum Deinstallieren von Data Sense von der Data Sense Benutzeroberfläche

Sie können Data Sense deinstallieren, um die Software dauerhaft vom Host zu entfernen, und im Falle einer Cloud-Bereitstellung löschen Sie die virtuelle Maschine / Instanz, auf der Data Sense bereitgestellt wurde. Durch das Löschen der Instanz werden alle indizierten Informationen gelöscht, die von Data Sense gescannt wurden. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["Erfahren Sie, wie"].



=== Audit-Protokollierung ist jetzt verfügbar, um die Historie der von Data Sense durchgeführten Aktionen zu verfolgen

Das Prüfprotokoll verfolgt die Managementaktivitäten, die Data Sense auf Dateien aus allen Arbeitsumgebungen und Datenquellen durchgeführt hat, die von Data Sense gescannt werden. Die Aktivitäten können vom Benutzer generiert (eine Datei löschen, eine Richtlinie erstellen usw.) oder durch Richtlinien generiert werden (Dateien können automatisch Etiketten hinzugefügt, Dateien automatisch gelöscht usw.).

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["Weitere Informationen zum Audit-Protokoll finden Sie hier"].



=== Neuer Filter für die Anzahl der sensiblen Kennungen auf der Seite Datenuntersuchung

Mit dem Filter „Anzahl der Kennungen“ können Sie Dateien mit einer bestimmten Anzahl sensibler Kennungen auflisten, einschließlich persönlicher Daten und sensibler personenbezogener Daten. Sie können einen Bereich wie 1-10 oder 501-1000 auswählen, um nur die Dateien anzuzeigen, die die Anzahl der sensiblen Kennungen enthalten.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Sehen Sie sich die Liste aller Filter an, mit denen Sie Ihre Daten untersuchen können"].



=== Jetzt können Sie vorhandene Richtlinien bearbeiten, die Sie erstellt haben

Wenn Sie eine Änderung an einer benutzerdefinierten Richtlinie vornehmen müssen, die Sie in der Vergangenheit erstellt haben, können Sie jetzt die Richtlinie bearbeiten, anstatt eine neue Richtlinie zu erstellen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["Lesen Sie, wie eine Richtlinie bearbeitet wird"].



== 11. Mai 2022 (Version 1.12.1)



=== Unterstützung für das Scannen von Daten in Google Drive-Konten hinzugefügt

Jetzt können Sie Ihre Google Drive-Konten zu Data Sense hinzufügen, um die Dokumente und Dateien von diesen Google Drive-Konten zu scannen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["Lesen Sie, wie Sie Ihre Google Drive-Konten scannen"].

Data Sense kann personenbezogene Daten (PII) innerhalb der folgenden Google-Dateitypen aus der Google Docs-Suite identifizieren -- Docs, Tabellen und Folien -- zusätzlich zu dem https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["Vorhandene Dateitypen"].



=== Ansicht auf Verzeichnisebene zur Seite Datenuntersuchung hinzugefügt

Neben dem Anzeigen und Filtern von Daten aus allen Dateien und Datenbanken können Sie jetzt auf der Seite „Datenuntersuchung“ Daten auf der Grundlage aller Daten in Ordnern und Freigaben anzeigen und filtern. Verzeichnisse werden für gescannte CIFS- und NFS-Freigaben sowie für OneDrive, SharePoint und Google Drive-Ordner indexiert. So können Sie nun Berechtigungen anzeigen und Ihre Daten auf der Verzeichnisebene verwalten. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Lesen Sie, wie Sie die Ansicht der Verzeichnisse Ihrer gescannten Daten auswählen"].



=== Erweitern Sie Gruppen, um die Benutzer/Mitglieder anzuzeigen, die über Berechtigungen zum Zugriff auf eine Datei verfügen

Im Rahmen der Data Sense-Berechtigungsfunktionen können Sie jetzt die Liste der Benutzer und Gruppen anzeigen, die Zugriff auf eine Datei haben. Jede Gruppe kann erweitert werden, um die Liste der Benutzer in der Gruppe anzuzeigen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["Lesen Sie, wie Sie Benutzer und Gruppen anzeigen, die Lese- und/oder Schreibberechtigungen für Ihre Dateien haben"].



=== Auf der Seite „Datenuntersuchung“ wurden zwei neue Filter hinzugefügt

* Mit dem Filter „Directory type“ können Sie Ihre Daten so verfeinern, dass nur Ordner oder Freigaben angezeigt werden. Die Ergebnisse werden auf der neuen Registerkarte *Directories* angezeigt.
* Mit dem Filter „Benutzer-/Gruppenberechtigungen“ können Sie die Dateien, Ordner und Freigaben auflisten, auf die ein bestimmter Benutzer oder eine Gruppe Lese- und/oder Schreibberechtigungen besitzt. Sie können mehrere Benutzer und/oder Gruppennamen auswählen oder einen Teilnamen eingeben.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Sehen Sie sich die Liste aller Filter an, mit denen Sie Ihre Daten untersuchen können"].



== 5. April 2022 (Version 1.11.1)



=== Vier neue Arten von australischen personenbezogenen Daten können durch Data Sense identifiziert werden

Data Sense kann Dateien identifizieren und kategorisieren, die die Australian TFN (Tax File Number), die Australian Driver's License Number, die Australian Medicare Number und die Australian Passport Number enthalten. link:reference-private-data-categories.html#types-of-personal-data["Sehen Sie alle Arten von personenbezogenen Daten an, die Data Sense in Ihren Daten identifizieren kann"].



=== Der globale Active Directory-Server kann jetzt ein LDAP-Server sein

Der globale Active Directory-Server, den Sie mit Data Sense integrieren, kann jetzt zusätzlich zu dem zuvor unterstützten DNS-Server ein LDAP-Server sein. link:task-add-active-directory-datasense.html["Weitere Informationen finden Sie hier"].
