---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: Erfahren Sie mehr über die Neuerungen bei der BlueXP Klassifizierung. 
---
= Neuerungen bei der BlueXP -Klassifizierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen bei der BlueXP Klassifizierung.



== 14 Juli 2025



=== Version 1.45

Diese BlueXP classification Klassifizierungsversion enthält Codeänderungen, die die Ressourcennutzung optimieren und:

.Verbesserter Workflow zum Hinzufügen von Dateifreigaben zum Scannen
Der Workflow zum Hinzufügen von Dateifreigaben zu einer Dateifreigabegruppe wurde vereinfacht. Der Prozess unterscheidet jetzt auch die CIFS-Protokollunterstützung basierend auf dem Authentifizierungstyp (Kerberos oder NTLM).

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Scannen von Dateifreigaben"].

.Erweiterte Informationen zum Dateieigentümer
Sie können jetzt weitere Informationen zu Dateibesitzern für erfasste Dateien auf der Registerkarte „Untersuchung“ anzeigen. Suchen Sie beim Anzeigen der Metadaten für eine Datei auf der Registerkarte „Untersuchung“ den Dateibesitzer und wählen Sie dann **Details anzeigen** aus, um den Benutzernamen, die E-Mail-Adresse und den SAM-Kontonamen anzuzeigen. Sie können auch andere Elemente anzeigen, die diesem Benutzer gehören. Diese Funktion ist nur in Arbeitsumgebungen mit Active Directory verfügbar.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten"].



== 10 Juni 2025



=== Version 1.44

Diese BlueXP -Klassifizierungsversion umfasst:

.Verbesserte Aktualisierungszeiten für das Governance-Dashboard
Die Aktualisierungszeiten für einzelne Komponenten des Governance-Dashboards wurden verbessert. Die folgende Tabelle zeigt die Aktualisierungshäufigkeit für jede Komponente.

[cols="1,1"]
|===
| Komponente | Aktualisierungszeiten 


| Alter der Daten | 24 Stunden 


| Kategorien | 24 Stunden 


| Datenüberblick | 5 Minuten 


| Doppelte Dateien | 2 Stunden 


| Dateitypen | 24 Stunden 


| Nicht-Geschäftsdaten | 2 Stunden 


| Öffnen Sie Berechtigungen | 24 Stunden 


| Gespeicherte Suchen | 2 Stunden 


| Sensible Daten und umfassende Berechtigungen | 24 Stunden 


| Größe von Daten | 24 Stunden 


| Veraltete Daten | 2 Stunden 


| Top-Datenspeicher nach Vertraulichkeitsstufe | 2 Stunden 
|===
Sie können den Zeitpunkt der letzten Aktualisierung anzeigen und die Komponenten „Doppelte Dateien“, „Nicht-Geschäftsdaten“, „Gespeicherte Suchen“, „Veraltete Daten“ und „Top-Datenrepositorys nach Vertraulichkeitsstufe“ manuell aktualisieren. Weitere Informationen zum Governance-Dashboard finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Zeigen Sie Governance-Details zu den in Ihrer Organisation gespeicherten Daten an"] .

.Leistungs- und Sicherheitsverbesserungen
Es wurden Verbesserungen vorgenommen, um die Leistung, den Speicherverbrauch und die Sicherheit der BlueXP-Klassifizierung zu verbessern.

.Fehlerbehebungen
Redis wurde aktualisiert, um die Zuverlässigkeit der BlueXP-Klassifizierung zu verbessern. Die BlueXP-Klassifizierung verwendet jetzt Elasticsearch, um die Genauigkeit der Dateianzahlberichterstattung während Scans zu verbessern.



== 12 Mai 2025



=== Version 1.43

Diese BlueXP -Klassifizierungsversion umfasst:

.Priorisieren Sie Klassifizierungs-Scans
Die BlueXP -Klassifizierung unterstützt die Möglichkeit, neben den nur-Mapping-Scans auch Karten- und Klassifikationsscans zu priorisieren, wodurch Sie auswählen können, welche Scans zuerst abgeschlossen werden. Die Priorisierung von Map & Classify-Scans wird während und vor Beginn der Scans unterstützt. Wenn Sie einen Scan priorisieren möchten, während er gerade läuft, werden sowohl die Mapping- als auch die Klassifikationsscans priorisiert.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorisieren Sie Scans"].

.Unterstützung für kanadische Datenkategorien für personenbezogene Daten (PII)
BlueXP -Klassifikations-Scans identifizieren kanadische PII-Datenkategorien. Diese Kategorien umfassen Bankdaten, Passnummern, Sozialversicherungsnummern, Führerscheinnummern und Krankenkartennummern für alle kanadischen Provinzen und Gebiete.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Kategorien personenbezogener Daten"].

.Benutzerdefinierte Klassifizierung (Vorschau)
Die BlueXP -Klassifizierung unterstützt benutzerdefinierte Klassifizierungen für Karten- und Klassifikations-Scans. Mit benutzerdefinierten Klassifizierungen können Sie BlueXP -Scans so anpassen, dass sie Daten erfassen, die speziell auf Ihr Unternehmen zugeschnitten sind, und dabei reguläre Ausdrücke verwenden. Diese Funktion befindet sich derzeit in der Vorschau.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Fügen Sie benutzerdefinierte Klassifizierungen hinzu"].

.Registerkarte gespeicherte Suchen
Die Registerkarte **Policen** wurde umbenanntlink:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Gespeicherte Suchen**"]. Die Funktionalität bleibt unverändert.

.Senden Sie Scanereignisse an die BlueXP  Timeline
BlueXP  Classification unterstützt das Senden von Klassifikationsereignissen (wenn ein Scan initiiert wird und wann er endet) an den link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  Zeitplan"^].

.Sicherheitsupdates
* Das Keras-Paket wurde aktualisiert, um Schwachstellen zu beheben (BDSA-2025-0107 und BDSA-2025-1984).
* Die Konfiguration der Docker Container wurde aktualisiert. Der Container hat keinen Zugriff mehr auf die Netzwerkschnittstellen des Hosts, um rohe Netzwerkpakete zu erstellen. Durch die Reduzierung unnötiger Zugriffe verringert das Update potenzielle Sicherheitsrisiken.


.Performance-Verbesserungen
Codeverbesserungen wurden implementiert, um die RAM-Nutzung zu reduzieren und die Gesamtleistung der BlueXP -Klassifizierung zu verbessern.

.Fehlerbehebungen
Fehler, die dazu geführt haben, dass StorageGRID-Scans fehlschlagen, dass die Filteroptionen für die Untersuchungsseite nicht geladen werden und die Datenermittlung, die für Prüfungen mit hohem Volumen nicht heruntergeladen werden sollte, wurden behoben.



== Bis 14. April 2025



=== Version 1.42

Diese BlueXP -Klassifizierungsversion umfasst:

.Massenscans für Arbeitsumgebungen
Die BlueXP -Klassifizierung unterstützt Massenvorgänge für Arbeitsumgebungen. Sie können Mapping Scans aktivieren, Map & Classify Scans aktivieren, Scans deaktivieren oder eine benutzerdefinierte Konfiguration über Volumes in der Arbeitsumgebung erstellen. Wenn Sie eine Auswahl für ein einzelnes Volume treffen, wird die Massenauswahl überschrieben. Um einen Massenvorgang durchzuführen, navigieren Sie zur Seite **Konfiguration** und wählen Sie aus.

.Untersuchungsbericht lokal herunterladen
BlueXP  Classification unterstützt die Möglichkeit, Datenermittlungsberichte lokal herunterzuladen, um sie im Browser anzuzeigen. Wenn Sie die lokale Option wählen, ist die Datenermittlung nur im CSV-Format verfügbar und zeigt nur die ersten 10,000 Datenzeilen an.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten mit der BlueXP -Klassifizierung"].



== 10 März 2025



=== Version 1.41

Diese BlueXP -Klassifizierungsversion enthält allgemeine Verbesserungen und Fehlerbehebungen. Die Lösung umfasst außerdem:

.Scanstatus
Die BlueXP -Klassifizierung verfolgt den Echtzeitfortschritt der Scans von _initial_ Mapping und Klassifikation auf einem Volume. Separate progressive Balken verfolgen die Mapping- und Klassifikations-Scans und zeigen einen Prozentsatz der insgesamt gescannten Dateien an. Sie können auch mit dem Mauszeiger auf eine Fortschrittsleiste zeigen, um die Anzahl der gescannten Dateien und die Gesamtdateien anzuzeigen. Durch das Verfolgen des Status Ihrer Scans erhalten Sie tiefere Einblicke in den Scanfortschritt, sodass Sie Ihre Scans besser planen und die Ressourcenzuweisung verstehen können.

Um den Status Ihrer Scans anzuzeigen, navigieren Sie in der BlueXP -Klassifizierung zu **Konfiguration**, und wählen Sie dann die **Konfiguration der Arbeitsumgebung**. Der Fortschritt wird für jedes Volume in der Zeile angezeigt.



== 19 Februar 2025



=== Version 1.40

Diese BlueXP -Klassifizierungsversion umfasst die folgenden Updates.

.Unterstützung für RHEL 9.5
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für Red hat Enterprise Linux 9.5. Dies gilt für alle manuellen On-Premises-Installationen von BlueXP -Klassifizierungen und Dark-Site-Bereitstellungen.

Für die folgenden Betriebssysteme ist die Verwendung der Podman-Container-Engine erforderlich, und sie erfordern eine BlueXP -Klassifizierung der Version 1.30 oder höher: Red hat Enterprise Linux der Version 8.8, 9.2, 9.0, 9.1, 8.10, 9.3, 9.4 und 9.5.

.Priorisieren Sie nur Mapping-Scans
Bei der Durchführung von nur-Mapping-Scans können Sie die wichtigsten Scans priorisieren. Diese Funktion hilft Ihnen, wenn Sie viele Arbeitsumgebungen haben und sicherstellen möchten, dass zuerst Scans mit hoher Priorität abgeschlossen werden.

Standardmäßig werden Scans basierend auf der Reihenfolge, in der sie initiiert werden, in die Warteschlange gestellt. Mit der Möglichkeit, Scans zu priorisieren, können Sie Scans an die Vorderseite der Warteschlange verschieben. Mehrere Scans können priorisiert werden. Die Priorität wird in der Reihenfolge „First-in“, „First-Out“ festgelegt. Das bedeutet, dass der erste von Ihnen priorisierte Scan an den Anfang der Warteschlange geht. Der zweite priorisierte Scan wird in der Warteschlange und so weiter.

Die Prioritätsachse wird einmalig vergeben. Automatische Neuscans von Zuordnungsdaten erfolgen in der Standardreihenfolge.

Die Priorisierung ist beschränkt auflink:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Nur-Mapping-Scans"^]; es ist nicht verfügbar für die Zuordnung und Klassifizierung von Scans.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorisieren Sie Scans"^].

.Wiederholen Sie alle Scans
Die BlueXP -Klassifizierung unterstützt die Möglichkeit, alle fehlgeschlagenen Scans im Batch-Modus erneut zu versuchen.

Sie können Scans in einem Batch-Vorgang mit der Funktion **Alle wiederholen** erneut versuchen. Wenn Klassifikationsscans aufgrund eines vorübergehenden Problems, wie z. B. eines Netzwerkausfalls, fehlschlagen, können Sie alle Scans gleichzeitig mit einer Taste wiederholen, anstatt sie einzeln erneut zu versuchen. Scans können so oft wie nötig wiederholt werden.

So wiederholen Sie alle Scans:

. Wählen Sie im BlueXP -Klassifizierungsmenü *Konfiguration*.
. Um alle fehlgeschlagenen Scans erneut zu versuchen, wählen Sie *Alle Scans wiederholen*.


.Verbesserte Genauigkeit des Kategorisierungsmodells
Die Genauigkeit des Machine-Learning-Modells für link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["Vordefinierte Kategorien"] hat sich um 11 % erhöht.



== 22 Januar 2025



=== Version 1.39

Diese BlueXP -Klassifizierungsversion aktualisiert den Exportprozess für den Datenuntersuchungsbericht. Diese Exportaktualisierung ist nützlich, um zusätzliche Analysen Ihrer Daten durchzuführen, zusätzliche Visualisierungen der Daten zu erstellen oder die Ergebnisse Ihrer Datenuntersuchung mit anderen zu teilen.

Zuvor war der Export des Berichts zur Untersuchung von Daten auf 10,000 Zeilen beschränkt. Mit dieser Version wurde das Limit entfernt, sodass Sie alle Ihre Daten exportieren können. Durch diese Änderung können Sie mehr Daten aus Ihren Datenermittlungsberichten exportieren, was Ihnen mehr Flexibilität bei der Datenanalyse bietet.

Sie können die Arbeitsumgebung, die Volumes, den Zielordner und entweder das JSON- oder CSV-Format auswählen. Der exportierte Dateiname enthält einen Zeitstempel, mit dem Sie den Zeitpunkt des Exportes der Daten identifizieren können.

Zu den unterstützten Arbeitsumgebungen gehören:

* Cloud Volumes ONTAP
* FSX für ONTAP
* ONTAP
* Gruppe freigeben


Das Exportieren von Daten aus dem Bericht zur Datenuntersuchung hat folgende Einschränkungen:

* Die maximale Anzahl der herunterzuladenen Datensätze beträgt 500 Millionen. Pro Typ (Dateien, Verzeichnisse und Tabellen)
* Eine Million Datensätze werden voraussichtlich etwa 35 Minuten für den Export benötigen.


Einzelheiten zur Datenermittlung und zum Bericht finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten"].



== Bis 16. Dezember 2024



=== Version 1.38

Diese BlueXP -Klassifizierungsversion enthält allgemeine Verbesserungen und Fehlerbehebungen.



== Bis 4. November 2024



=== Version 1.37

Diese BlueXP -Klassifizierungsversion umfasst die folgenden Updates.

.Unterstützung für RHEL 8.10
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für Red hat Enterprise Linux 8.10. Dies gilt für alle manuellen On-Premises-Installationen von BlueXP -Klassifizierungen und Dark-Site-Bereitstellungen.

Für die folgenden Betriebssysteme ist die Verwendung der Podman-Container-Engine erforderlich, und sie erfordern eine BlueXP -Klassifizierung der Version 1.30 oder höher: Red hat Enterprise Linux der Version 8.8, 9.2, 9.0, 9.1, 8.10, 9.3 und 9.4.

Erfahren Sie mehr über https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP Klassifizierung"].

.Unterstützung für NFS v4.1
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für NFS v4.1.

Erfahren Sie mehr über https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP Klassifizierung"].



== 10 Oktober 2024



=== Version 1.36

.Unterstützung für RHEL 9.4
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für Red hat Enterprise Linux 9.4. Dies gilt für alle manuellen On-Premises-Installationen von BlueXP -Klassifizierungen und Dark-Site-Bereitstellungen.

Für die folgenden Betriebssysteme ist die Verwendung der Podman-Container-Engine erforderlich, und sie erfordern eine BlueXP -Klassifikation der Version 1.30 oder höher: Red hat Enterprise Linux der Version 8.8, 9.3, 9.1, 9.2, 9.0 und 9.4.

Weitere Informationen zu https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Übersicht über Implementierungen zur BlueXP Klassifizierung"].

.Verbesserte Scanleistung
Diese Version bietet eine verbesserte Scanleistung.



== 2 September 2024



=== Version 1.35

.Scannen von StorageGRID-Daten
Die BlueXP -Klassifizierung unterstützt das Scannen von Daten in StorageGRID.

Weitere Informationen finden Sie unter link:task-scanning-storagegrid.html["Scannen von StorageGRID-Daten"].



== 05 August 2024



=== Version 1.34

Diese BlueXP -Klassifizierungsversion umfasst das folgende Update.

.Wechseln Sie von CentOS zu Ubuntu
BlueXP  Classification hat sein Linux-Betriebssystem für Microsoft Azure und Google Cloud Platform (GCP) von CentOS 7.9 auf Ubuntu 22.04 aktualisiert.

Einzelheiten zur Bereitstellung finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["Installieren Sie auf einem Linux-Host mit Internetzugang und bereiten Sie das Linux-Host-System vor"].



== 01 Juli 2024



=== Version 1.33

.Ubuntu unterstützt
Diese Version unterstützt die Ubuntu 24.04 Linux-Plattform.

.Durch Mapping-Scans werden Metadaten erfasst
Die folgenden Metadaten werden während der Mapping-Scans aus Dateien extrahiert und auf den Dashboards Governance, Compliance und Investigation angezeigt:

* Arbeitsumgebung
* Art der Arbeitsumgebung
* Storage Repository
* Dateityp
* Genutzte Kapazität
* Anzahl der Dateien
* Dateigröße
* Dateierstellung
* Letzter Zugriff auf die Datei
* Datei zuletzt geändert
* Erkannte Zeit der Datei
* Extraktion von Berechtigungen


.Zusätzliche Daten in Dashboards
Diese Version aktualisiert, welche Daten während der Mapping-Scans in den Dashboards für Governance, Compliance und Untersuchung angezeigt werden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Was ist der Unterschied zwischen Mapping- und Klassifikationsscans"].



== 05 Juni 2024



=== Version 1.32

.Neue Zuordnungsstatus-Spalte auf der Seite Konfiguration
In diesem Release wird jetzt eine neue Zuordnungsstatus-Spalte auf der Seite Konfiguration angezeigt. Mit der neuen Spalte können Sie feststellen, ob die Zuordnung ausgeführt, in die Warteschlange gestellt, angehalten oder mehr ist.

Erläuterungen zu den Status finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["Scaneinstellungen ändern"].



== 15 Mai 2024



=== Version 1.31

.Klassifizierung ist als zentraler Service in BlueXP erhältlich
Die BlueXP Klassifizierung ist jetzt als zentrale Funktion in BlueXP ohne Aufpreis für bis zu 500 tib gescannte Daten verfügbar. Es ist keine Klassifizierungslizenz oder kostenpflichtiges Abonnement erforderlich. Da wir uns bei der BlueXP Klassifizierungsfunktion auf das Scannen von NetApp Storage-Systemen mit dieser neuen Version konzentrieren, stehen einige ältere Funktionen nur Kunden zur Verfügung, die zuvor für eine Lizenz bezahlt hatten. Die Nutzung dieser älteren Funktionen läuft ab, wenn der bezahlte Vertrag sein Enddatum erreicht.

link:reference-free-paid.html["Erfahren Sie mehr über die veralteten Funktionen"].



== 01. April 2024



=== Version 1.30

.Unterstützung für die Klassifizierung von RHEL v8.8 und v9.3 BlueXP hinzugefügt
Diese Version bietet Unterstützung für Red hat Enterprise Linux v8.8 und v9.3 zusätzlich zu zuvor unterstützten 9.x, für die Podman anstelle der Docker Engine erforderlich ist. Dies gilt für jede manuelle On-Premises-Installation der BlueXP Klassifizierung.

Für die folgenden Betriebssysteme ist die Verwendung der Podman Container-Engine erforderlich. Sie erfordern die BlueXP-Klassifikation Version 1.30 oder höher: Red hat Enterprise Linux Version 8.8, 9.0, 9.1, 9.2 und 9.3.

Weitere Informationen zu https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Übersicht über Implementierungen zur BlueXP Klassifizierung"].

Die BlueXP Klassifizierung wird unterstützt, wenn Sie den Connector auf einem lokalen RHEL 8- oder 9-Host installieren. Es wird nicht unterstützt, wenn sich der RHEL 8- oder RHEL 9-Host in AWS, Azure oder Google Cloud befindet.

.Option zum Aktivieren der Sammlung des Überwachungsprotokolls entfernt
Die Option zum Aktivieren der Überwachungsprotokollsammlung wurde deaktiviert.

.Scangeschwindigkeit verbessert
Die Scanleistung auf sekundären Scannerknoten wurde verbessert. Sie können weitere Scannerknoten hinzufügen, wenn Sie zusätzliche Verarbeitungsleistung für Ihre Scans benötigen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installieren Sie die BlueXP Klassifizierung auf einem Host mit Internetzugang"].

.Automatische Upgrades
Wenn Sie die BlueXP Klassifizierung auf einem System mit Internetzugang implementiert haben, wird das System automatisch aktualisiert. Zuvor erfolgte das Upgrade nach einer bestimmten Zeit seit der letzten Benutzeraktivität. Mit dieser Version wird die BlueXP Klassifizierung automatisch aktualisiert, wenn die lokale Zeit zwischen 1:00 und 5:00 UHR MORGENS liegt. Wenn die lokale Zeit außerhalb dieser Stunden liegt, erfolgt die Aktualisierung nach einem bestimmten Zeitraum seit der letzten Benutzeraktivität. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installation auf einem Linux-Host mit Internetzugang"].

Wenn Sie die BlueXP Klassifizierung ohne Internetzugang implementiert haben, müssen Sie ein Upgrade manuell vornehmen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["BlueXP Klassifizierung auf einem Linux-Host ohne Internetzugang installieren"].



== 04 März 2024



=== Version 1.29

.Jetzt können Sie Scandaten ausschließen, die sich in bestimmten Datenquellen-Verzeichnissen befinden
Wenn die BlueXP Klassifizierung Scandaten in bestimmten Quellverzeichnissen ausschließen soll, können Sie diese Verzeichnisnamen zu einer Konfigurationsdatei hinzufügen, die durch die BlueXP Klassifizierung verarbeitet wird. Mit dieser Funktion können Sie verhindern, dass Verzeichnisse gescannt werden, die unnötig sind oder zu falsch positiven Ergebnissen von persönlichen Daten führen würden.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["Weitere Informationen ."].

.Unterstützung für extra große Instanzen ist jetzt qualifiziert
Wenn Sie mehr als 250 Millionen Dateien durch eine BlueXP Klassifizierung scannen möchten, können Sie eine besonders große Instanz in Ihrer Cloud-Implementierung oder vor-Ort-Installation verwenden. Dieser Systemtyp kann bis zu 500 Millionen Dateien scannen.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["Weitere Informationen ."].



== 10 Januar 2024



=== Version 1.27

.Die Ergebnisse der Untersuchungsseite zeigen die Gesamtgröße zusätzlich zur Gesamtanzahl der Elemente an
Die gefilterten Ergebnisse auf der Seite Untersuchung zeigen die Gesamtgröße der Elemente zusätzlich zur Gesamtanzahl der Dateien an. Dies kann beim Verschieben von Dateien, beim Löschen von Dateien und vielem mehr helfen.

.Zusätzliche Gruppen-IDs als „für Organisation offen“ konfigurieren
Nun können Sie Gruppen-IDs in NFS so konfigurieren, dass sie direkt aus der BlueXP-Klassifizierung als „Open to Organization“ betrachtet werden, wenn die Gruppe ursprünglich nicht mit dieser Berechtigung festgelegt wurde. Alle Dateien und Ordner, denen diese Gruppen-IDs angehängt sind, werden auf der Seite „Untersuchungsdetails“ als „für Organisation offen“ angezeigt. Informieren Sie sich darüber https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["Zusätzliche Gruppen-IDs als „für Organisation offen“ hinzufügen"].



== Bis 14. Dezember 2023



=== Version 1.26.6

Diese Version enthält einige kleinere Verbesserungen.

Die Version hat außerdem die folgenden Optionen entfernt:

* Die Option zum Aktivieren der Überwachungsprotokollsammlung wurde deaktiviert.
* Bei der Untersuchung der Verzeichnisse steht die Möglichkeit zur Berechnung der Anzahl der personenbezogenen Daten (PII) nach Verzeichnissen nicht zur Verfügung. Siehe link:task-investigate-data.html["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten"].
* Die Option zur Integration von Daten mit AIP-Labels (Azure Information Protection) wurde deaktiviert. Siehe link:task-org-private-data.html["Private Daten organisieren"].




== 06. November 2023



=== Version 1.26.3

Die folgenden Probleme wurden in dieser Version behoben

* Es wurde eine Inkonsistenz bei der Darstellung der Anzahl der vom System gescannten Dateien in Dashboards behoben.
* Verbesserte das Scanverhalten durch die Handhabung und Berichterstattung von Dateien und Verzeichnissen mit Sonderzeichen im Namen und Metadaten.




== 04 Oktober 2023



=== Version 1.26

.Unterstützung lokaler Installationen von BlueXP Klassifizierungen auf RHEL Version 9
Red hat Enterprise Linux Versionen 8 und 9 unterstützen nicht die Docker Engine, die für die Installation der BlueXP Klassifikation erforderlich war. Wir unterstützen jetzt die Installation der BlueXP Klassifizierung auf RHEL 9.0, 9.1 und 9.2 mit Podman Version 4 oder höher als Container-Infrastruktur. Wenn in Ihrer Umgebung die neuesten Versionen von RHEL erforderlich sind, können Sie Podman jetzt auch die BlueXP-Klassifizierung (Version 1.26 oder höher) installieren.

Derzeit werden bei Verwendung von RHEL 9.x. keine Dark-Site-Installationen oder verteilte Scanumgebungen (mit Master- und Remote-Scanner-Nodes) unterstützt



== 05 September 2023



=== Version 1.25

.Kleine und mittlere Bereitstellungen sind vorübergehend nicht verfügbar
Wenn Sie eine Instanz der BlueXP Klassifizierung in AWS implementieren, ist die Option *Deploy > Configuration* und die Auswahl einer kleinen oder mittelgroßen Instanz derzeit nicht verfügbar. Sie können die Instanz weiterhin mit der Größe der großen Instanz bereitstellen, indem Sie *Deploy > Deploy* auswählen.

.Verwenden Sie Tags auf bis zu 100,000 Elemente auf der Seite Untersuchungsergebnisse
In der Vergangenheit konnten Sie auf der Seite Untersuchungsergebnisse (20 Elemente) jeweils nur Tags auf eine Seite anwenden. Jetzt können Sie *alle* Elemente auf den Seiten Untersuchungsergebnisse auswählen und Tags auf alle Elemente anwenden - bis zu 100,000 Elemente gleichzeitig. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["Erfahren Sie, wie"].

.Identifizieren Sie duplizierte Dateien mit einer Mindestdateigröße von 1 MB
Mit der BlueXP Klassifizierung werden duplizierte Dateien nur bei Dateien identifiziert, die 50 MB oder mehr betragen. Nun können duplizierte Dateien, die mit 1 MB beginnen, identifiziert werden. Sie können die Filter der Untersuchungsseite „Dateigröße“ zusammen mit „Duplikate“ verwenden, um zu sehen, welche Dateien einer bestimmten Größe in Ihrer Umgebung dupliziert werden.



== 17 Juli 2023



=== Version 1.24

.Zwei neue Arten deutscher personenbezogener Daten werden durch die BlueXP Klassifizierung identifiziert
Mit der BlueXP Klassifizierung können Dateien identifiziert und kategorisiert werden, die die folgenden Datentypen enthalten:

* Personalausweisnummer
* Sozialversicherungsnummer


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Hier können Sie alle Arten von personenbezogenen Daten einsehen, die durch die BlueXP Klassifizierung in Ihren Daten identifiziert werden können"].

.Die BlueXP Klassifizierung wird im eingeschränkten und privaten Modus vollständig unterstützt
Die BlueXP Klassifizierung wird jetzt vollständig auf Websites ohne Internetzugang (privater Modus) und mit eingeschränktem Outbound-Internetzugang (eingeschränkter Modus) unterstützt. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Weitere Informationen zu den BlueXP Implementierungsmodi für den Connector"^].

.Fähigkeit zum überspringen von Versionen beim Upgrade einer Installation von BlueXP Klassifizierung im Private-Modus
Sie können jetzt ein Upgrade auf eine neuere Version der BlueXP Klassifizierung durchführen, auch wenn diese nicht sequenziell ist. Das heißt, die aktuelle Einschränkung für das Upgrade der BlueXP Klassifizierung um jeweils eine Version ist nicht mehr erforderlich. Diese Funktion ist ab Version 1.24 relevant.

.Die BlueXP Klassifizierungs-API ist jetzt verfügbar
Mithilfe der BlueXP Klassifizierungs-API können Sie Aktionen durchführen, Abfragen erstellen und Informationen zu den zu scannenden Daten exportieren. Die interaktive Dokumentation ist über Swagger verfügbar. Die Dokumentation ist in mehrere Kategorien unterteilt, darunter Untersuchung, Compliance, Governance und Konfiguration. Jede Kategorie dient als Verweis auf die Registerkarten in der BlueXP Klassifizierungs-UI.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["Erfahren Sie mehr über die BlueXP Klassifizierungs-APIs"].



== 06 Juni 2023



=== Version 1.23

.Japanisch wird jetzt bei der Suche nach Datenfachnamen unterstützt
Japanische Namen können jetzt bei der Suche nach dem Namen eines Studienteilnehmers als Antwort auf einen Antrag auf Zugang zu einem Datengegenstand (Data Subject Access Request, DSAR) eingegeben werden. Sie können eine https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["Bericht für Anforderung von Datenfachzugriff"] mit den daraus resultierenden Informationen erstellen. Sie können auch japanische Namen in das eingeben https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Filter „Betroffene“ auf der Seite „Datenuntersuchung“"], um Dateien zu identifizieren, die den Namen des Studienteilnehmers enthalten.

.Ubuntu ist jetzt eine unterstützte Linux-Distribution, auf der Sie BlueXP Klassifizierung installieren können
Ubuntu 22.04 wurde als unterstütztes Betriebssystem für die BlueXP Klassifizierung qualifiziert. Sie können die BlueXP-Klassifizierung auf einem Ubuntu Linux-Host in Ihrem Netzwerk oder auf einem Linux-Host in der Cloud installieren, wenn Sie Version 1.23 des Installers verwenden. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Erfahren Sie, wie Sie die BlueXP Klassifizierung auf einem Host installieren, auf dem Ubuntu installiert ist"].

.Red hat Enterprise Linux 8.6 und 8.7 werden bei neuen BlueXP Klassifizierungssysteminstallationen nicht mehr unterstützt
Diese Versionen werden bei neuen Bereitstellungen nicht unterstützt, da Red hat Docker nicht mehr unterstützt, was eine Voraussetzung ist. Wenn Sie eine vorhandene BlueXP Klassifizierungsmaschine unter RHEL 8.6 oder 8.7 verwenden, unterstützt NetApp Ihre Konfiguration weiterhin.

.Die BlueXP Klassifizierung kann als FPolicy Collector konfiguriert werden, um FPolicy Ereignisse von ONTAP Systemen zu empfangen
Sie können Audit-Protokolle für den Dateizugriff in Ihrem BlueXP Klassifizierungssystem für Dateizugriffsereignisse auf Volumes in Ihren Arbeitsumgebungen erfassen. Die BlueXP Klassifizierung kann die folgenden Arten von FPolicy Ereignissen und die Benutzer erfassen, die die Aktionen an Ihren Dateien durchgeführt haben: Erstellen, Lesen, Schreiben, Löschen, Umbenennen, Eigentümer/Berechtigungen ändern und SACL/DACL ändern.

.Data Sense BYOL-Lizenzen werden nun in Dark Sites unterstützt
Sie können jetzt Ihre Data Sense BYOL-Lizenz in das Digital Wallet von BlueXP auf einer Dark Site hochladen, sodass Sie bei einer geringen Lizenzierungsbeschränkung benachrichtigt werden.



== 03. April 2023



=== Version 1.22

.Neuer Data Discovery Assessment Report
Der Data Discovery Assessment Report bietet eine allgemeine Analyse Ihrer gescannten Umgebung, um die Ergebnisse des Systems hervorzuheben und Problembereiche und mögliche Schritte zur Problembehebung aufzuzeigen. Ziel dieses Berichts ist es, ein Bewusstsein für Bedenken im Zusammenhang mit der Data Governance, Schwachstellen bei der Datensicherheit und Lücken in der Daten-Compliance in Ihrem Datensatz zu schaffen. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Erfahren Sie, wie Sie den Data Discovery Assessment Report erstellen und verwenden"].

.Möglichkeit zur Implementierung der BlueXP Klassifizierung auf kleineren Instanzen in der Cloud
Bei der Implementierung der BlueXP Klassifizierung aus einem BlueXP Connector in einer AWS-Umgebung können Sie nun zwischen zwei kleineren Instanztypen wählen als bei der Standardinstanz. Wenn Sie eine kleine Umgebung scannen, können Sie hier Cloud-Kosten sparen. Allerdings gibt es einige Einschränkungen bei der Verwendung der kleineren Instanz. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Anzeigen der verfügbaren Instanztypen und Einschränkungen"].

.Eigenständiges Skript steht jetzt zur Verfügung, um Ihr Linux-System vor der Installation der BlueXP Klassifizierung zu qualifizieren
Wenn Sie unabhängig von der Ausführung der BlueXP Klassifizierungssysteminstallation überprüfen möchten, ob Ihr Linux-System alle Voraussetzungen erfüllt, steht Ihnen ein separates Skript zur Verfügung, das nur die Voraussetzungen testet. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Erfahren Sie, wie Sie überprüfen können, ob Ihr Linux-Host bereit ist, die BlueXP Klassifizierung zu installieren"].



== 07 März 2023



=== Version 1.21

.Neue Funktionen, mit denen Sie Ihre eigenen benutzerdefinierten Kategorien von der BlueXP Klassifizierungs-UI hinzufügen können
Mit der BlueXP Klassifizierung können Sie jetzt Ihre eigenen benutzerdefinierten Kategorien hinzufügen, sodass die Dateien nach der BlueXP Klassifizierung ermittelt werden, die zu diesen Kategorien passen. Die BlueXP -Klassifizierung hat viele https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Vordefinierte Kategorien"], so dass Sie mit dieser Funktion benutzerdefinierte Kategorien hinzufügen können, um zu ermitteln, wo für Ihr Unternehmen spezifische Informationen in Ihren Daten gefunden werden.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Weitere Informationen ."^].

.Sie können jetzt benutzerdefinierte Schlüsselwörter aus der BlueXP Klassifizierungs-UI hinzufügen
Mit der BlueXP Klassifizierung konnten benutzerdefinierte Schlüsselwörter hinzugefügt werden, die durch die BlueXP Klassifizierung bei zukünftigen Scans ab und an identifiziert werden. Sie mussten sich jedoch beim BlueXP Klassifizierungs-Linux-Host anmelden und eine Befehlszeilenschnittstelle verwenden, um die Schlüsselwörter hinzuzufügen. In dieser Version können benutzerdefinierte Schlüsselwörter in der BlueXP Klassifizierungs-UI hinzugefügt werden. Dies macht es sehr einfach, diese Schlüsselwörter hinzuzufügen und zu bearbeiten.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Weitere Informationen zum Hinzufügen benutzerdefinierter Schlüsselwörter finden Sie in der BlueXP Klassifizierungs-UI"^].

.Möglichkeit zur BlueXP Klassifizierung *nicht* von Dateien, wenn die „Uhrzeit des letzten Zugriffs“ geändert wird
Wenn die BlueXP Klassifizierung keine ausreichenden „Schreib“-Berechtigungen besitzt, scannt das System standardmäßig keine Dateien in Ihren Volumes, da die BlueXP Klassifizierung die „letzte Zugriffszeit“ nicht auf den ursprünglichen Zeitstempel zurücksetzen kann. Wenn es Ihnen jedoch egal ist, ob die letzte Zugriffszeit in Ihren Dateien auf die ursprüngliche Uhrzeit zurückgesetzt wird, können Sie dieses Verhalten auf der Konfigurationsseite außer Kraft setzen, damit die BlueXP Klassifizierung die Volumes unabhängig von den Berechtigungen scannt.

In Verbindung mit dieser Funktion steht nun ein neuer Filter namens „Scan Analysis Event“ zur Verfügung, mit dem Sie die Dateien anzeigen können, die nicht klassifiziert wurden, weil die BlueXP Klassifizierung den Zeitpunkt des letzten Zugriffs nicht rückgängig machen konnte, oder die Dateien, die klassifiziert wurden, obwohl die BlueXP Klassifizierung beim letzten Zugriff nicht rückgängig gemacht wurde.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html["Erfahren Sie mehr über den „Zeitstempel des letzten Zugriffs“ und die Berechtigungen, die die BlueXP Klassifizierung erfordert"].

.Drei neue Arten von personenbezogenen Daten werden durch die BlueXP Klassifizierung identifiziert
Mit der BlueXP Klassifizierung können Dateien identifiziert und kategorisiert werden, die die folgenden Datentypen enthalten:

* Botswana Identity Card (Omang)-Nummer
* Botswana Passnummer
* Personalausweis für die nationale Registrierung in Singapur (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Hier können Sie alle Arten von personenbezogenen Daten einsehen, die durch die BlueXP Klassifizierung in Ihren Daten identifiziert werden können"].

.Aktualisierte Funktionalität für Verzeichnisse
* Die Option „leichter CSV-Bericht“ für Datenuntersuchungsberichte enthält jetzt Informationen aus Verzeichnissen.
* Der Zeitfilter „Letzter Zugriff“ zeigt jetzt die zuletzt verwendete Zeit für Dateien und Verzeichnisse an.


.Installationsverbesserungen führen zu
* Der BlueXP Klassifizierungs-Installer für Standorte ohne Internetzugang (Dark Sites) führt jetzt eine Vorabprüfung durch, um sicherzustellen, dass Ihre System- und Netzwerkanforderungen für eine erfolgreiche Installation bestehen.
* Die Protokolldateien der Installationsaudits werden jetzt gespeichert und in geschrieben `/ops/netapp/install_logs`.




== 05 Februar 2023



=== Version 1.20

.Möglichkeit, Policy-basierte Benachrichtigungs-E-Mails an jede beliebige E-Mail-Adresse zu senden
In früheren Versionen der BlueXP Klassifizierung können Sie E-Mail-Benachrichtigungen an die BlueXP Benutzer Ihres Kontos senden, wenn bestimmte kritische Richtlinien Ergebnisse liefern. Mit dieser Funktion erhalten Sie Benachrichtigungen zum Schutz Ihrer Daten, wenn Sie nicht online sind. Jetzt können Sie auch E-Mail-Benachrichtigungen von Policies an andere Benutzer senden - bis zu 20 E-Mail-Adressen - die nicht in Ihrem BlueXP-Konto sind.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["Erfahren Sie mehr über das Senden von E-Mail-Benachrichtigungen basierend auf Policy-Ergebnissen"].

.Sie können jetzt persönliche Muster über die BlueXP Klassifizierungs-UI hinzufügen
Mit der BlueXP Klassifizierung konnten individuelle „persönliche Daten“ hinzugefügt werden, die durch die BlueXP Klassifizierung in künftigen Scans schon seit einiger Zeit erkannt werden. Sie mussten sich jedoch beim BlueXP Klassifizierungs-Linux-Host anmelden und eine Befehlszeile verwenden, um die benutzerdefinierten Muster hinzuzufügen. In dieser Version besteht die Möglichkeit, persönliche Muster mit einem regex hinzuzufügen, indem sie die BlueXP Klassifizierungs-UI verwenden. Damit ist es sehr einfach, diese benutzerdefinierten Muster hinzuzufügen und zu bearbeiten.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["Weitere Informationen zum Hinzufügen benutzerdefinierter Muster erhalten Sie über die BlueXP Klassifizierungs-UI"^].

.Möglichkeit zum Verschieben von 15 Millionen Dateien mithilfe der BlueXP Klassifizierung
In der Vergangenheit können Sie durch die BlueXP Klassifizierung maximal 100,000 Quelldateien auf eine beliebige NFS-Freigabe verschieben. Jetzt können Sie bis zu 15 Millionen Dateien gleichzeitig verschieben. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["Weitere Informationen zum Verschieben von Quelldateien mithilfe der BlueXP Klassifizierung"].

.Fähigkeit, die Anzahl der Benutzer zu sehen, die Zugriff auf SharePoint Online-Dateien haben
Der Filter "Anzahl der Benutzer mit Zugriff" unterstützt nun Dateien, die in SharePoint Online-Repositorys gespeichert sind. In der Vergangenheit wurden nur Dateien auf CIFS Shares unterstützt. Beachten Sie, dass SharePoint-Gruppen, die nicht auf Active Directory basieren, derzeit nicht in diesen Filter gezählt werden.

.Der Aktionsstatus wurde um einen neuen Status „Teilerfolg“ erweitert
Der neue Status „Teilsuccess“ zeigt an, dass eine BlueXP-Klassifizierungsaktion abgeschlossen ist und einige Elemente fehlgeschlagen sind und einige Elemente erfolgreich waren, z. B. wenn Sie 100 Dateien verschieben oder löschen. Außerdem wurde der Status „Fertig“ in „Erfolg“ umbenannt. In der Vergangenheit können im Status „Fertig“ Aktionen aufgeführt werden, die erfolgreich waren und die fehlgeschlagen sind. Der Status „Erfolg“ bedeutet nun, dass alle Aktionen erfolgreich auf allen Elementen durchgeführt wurden. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Lesen Sie, wie Sie das Fenster „Aktionsstatus“ anzeigen"].



== 09 Januar 2023



=== Version 1.19

.Möglichkeit, ein Diagramm von Dateien anzuzeigen, die sensible Daten enthalten und die übermäßig permissiv sind
Das Governance Dashboard hat einen neuen Bereich mit „_sensitiven Daten“ und „Wide Permissions_“ hinzugefügt, der eine Heatmap mit Dateien enthält, die vertrauliche Daten (einschließlich sensibler und sensibler personenbezogener Daten) enthalten und die zu permissiv sind. Auf diese Weise können Sie erkennen, wo Sie möglicherweise Risiken mit sensiblen Daten haben. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Weitere Informationen ."].

.Auf der Seite „Datenuntersuchung“ stehen drei neue Filter zur Verfügung
Es stehen neue Filter zur Verfügung, um die Ergebnisse zu verfeinern, die auf der Seite „Datenuntersuchung“ angezeigt werden:

* Der Filter „Anzahl der Benutzer mit Zugriff“ zeigt an, welche Dateien und Ordner für eine bestimmte Anzahl von Benutzern geöffnet sind. Sie können einen Zahlenbereich auswählen, um die Ergebnisse zu verfeinern, z. B. um zu sehen, auf welche Dateien 51-100 Benutzer zugreifen können.
* Mit den Filtern „erstellte Zeit“, „entdeckte Zeit“, „Zuletzt geändert“ und „Letzter Zugriff“ können Sie jetzt einen benutzerdefinierten Datumsbereich erstellen, anstatt nur einen vordefinierten Zeitraum von Tagen auszuwählen. Sie können beispielsweise nach Dateien mit einer "Erstellungszeit" "älter als 6 Monate" oder mit einem "Letzter geändert" Datum innerhalb der "letzten 10 Tage" suchen.
* Mit dem Filter „Dateipfad“ können Sie nun Pfade festlegen, die Sie aus den gefilterten Abfrageergebnissen ausschließen möchten. Wenn Sie Pfade zum ein- und Ausschließen bestimmter Daten eingeben, findet die BlueXP Klassifizierung zuerst alle Dateien in den eingeschlossenen Pfaden, dann entfernt sie Dateien aus ausgeschlossenen Pfaden und zeigt dann die Ergebnisse an.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Sehen Sie sich die Liste aller Filter an, mit denen Sie Ihre Daten untersuchen können"].

.Durch die BlueXP Klassifizierung kann die japanische individuelle Nummer identifiziert werden
Durch die BlueXP Klassifizierung können Dateien identifiziert und kategorisiert werden, die die japanische individuelle Nummer (auch „Meine Nummer“) enthalten. Dies umfasst sowohl die persönliche als auch die eigene Firmennummer. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Hier können Sie alle Arten von personenbezogenen Daten einsehen, die durch die BlueXP Klassifizierung in Ihren Daten identifiziert werden können"].
