= Version 1.44
:allow-uri-read: 




=== Version 1.44

Diese BlueXP -Klassifizierungsversion umfasst:

.Verbesserte Aktualisierungszeiten für das Governance-Dashboard
Die Aktualisierungszeiten für einzelne Komponenten des Governance-Dashboards wurden verbessert. Die folgende Tabelle zeigt die Aktualisierungshäufigkeit für jede Komponente.

[cols="1,1"]
|===
| Komponente | Aktualisierungszeiten 


| Alter der Daten | 24 Stunden 


| Kategorien | 24 Stunden 


| Datenüberblick | 5 Minuten 


| Doppelte Dateien | 2 Stunden 


| Dateitypen | 24 Stunden 


| Nicht-Geschäftsdaten | 2 Stunden 


| Öffnen Sie Berechtigungen | 24 Stunden 


| Gespeicherte Suchen | 2 Stunden 


| Sensible Daten und umfassende Berechtigungen | 24 Stunden 


| Größe von Daten | 24 Stunden 


| Veraltete Daten | 2 Stunden 


| Top-Datenspeicher nach Vertraulichkeitsstufe | 2 Stunden 
|===
Sie können den Zeitpunkt der letzten Aktualisierung anzeigen und die Komponenten „Doppelte Dateien“, „Nicht-Geschäftsdaten“, „Gespeicherte Suchen“, „Veraltete Daten“ und „Top-Datenrepositorys nach Vertraulichkeitsstufe“ manuell aktualisieren. Weitere Informationen zum Governance-Dashboard finden Sie unter xref:task-controlling-governance-data.html[Zeigen Sie Governance-Details zu den in Ihrer Organisation gespeicherten Daten an] .

.Leistungs- und Sicherheitsverbesserungen
Es wurden Verbesserungen vorgenommen, um die Leistung, den Speicherverbrauch und die Sicherheit der BlueXP-Klassifizierung zu verbessern.

.Fehlerbehebungen
Redis wurde aktualisiert, um die Zuverlässigkeit der BlueXP-Klassifizierung zu verbessern. Die BlueXP-Klassifizierung verwendet jetzt Elasticsearch, um die Genauigkeit der Dateianzahlberichterstattung während Scans zu verbessern.
