= Version 1.45
:allow-uri-read: 




=== Version 1.45

Diese BlueXP classification Klassifizierungsversion enthält Codeänderungen, die die Ressourcennutzung optimieren und:

.Verbesserter Workflow zum Hinzufügen von Dateifreigaben zum Scannen
Der Workflow zum Hinzufügen von Dateifreigaben zu einer Dateifreigabegruppe wurde vereinfacht. Der Prozess unterscheidet jetzt auch die CIFS-Protokollunterstützung basierend auf dem Authentifizierungstyp (Kerberos oder NTLM).

Weitere Informationen finden Sie unter xref:task-scanning-file-shares.html[Scannen von Dateifreigaben].

.Erweiterte Informationen zum Dateieigentümer
Sie können jetzt weitere Informationen zu Dateibesitzern für erfasste Dateien auf der Registerkarte „Untersuchung“ anzeigen. Suchen Sie beim Anzeigen der Metadaten einer Datei auf der Registerkarte „Untersuchung“ den Dateibesitzer und wählen Sie „Details anzeigen“, um Benutzername, E-Mail-Adresse und SAM-Kontonamen anzuzeigen. Sie können auch andere Elemente anzeigen, die diesem Benutzer gehören. Diese Funktion ist nur in Arbeitsumgebungen mit Active Directory verfügbar.

Weitere Informationen finden Sie unter xref:task-investigate-data.html[Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten].
